/* Maps a menu item name to a dish-photo key (first matching rule wins). Photos live in src/assets/dishes/<key>.jpg.
   Photos show the kind of dish, not the venue's exact plate. */
const RULES = [
  [/dosa|uttapam|uthappam/, 'dosa'],
  [/idli/, 'idli'],
  [/vada pav|dabeli/, 'vadapav'],
  [/dahi vada|dahi bhalla|dahi bhalle|dahi ke/, 'dahivada'],
  [/medu vada|vada|bonda/, 'vada'],
  [/kheema|keema/, 'kheema'],
  [/pav bhaji|bhaji pav/, 'pavbhaji'],
  [/haleem/, 'haleem'],
  [/biryani|pulao|pulav/, 'biryani'],
  [/butter chicken|murgh makhani/, 'butterchicken'],
  [/chole/, 'chole'],
  [/paneer|lababdar|pasanda/, 'paneer'],
  [/dal |dal$|makhani|tadka/, 'dal'],
  [/kathi|roll|wrap/, 'wrap'],
  [/kebab|tikka|seekh|galouti|burra|boti|sholay/, 'kebab'],
  [/paratha|parantha|thepla|rotla/, 'paratha'],
  [/naan|roti|rumali|kulcha|bhatura|poori|sheermal/, 'naan'],
  [/pani puri/, 'panipuri'],
  [/raj kachori|kachori/, 'kachori'],
  [/samosa/, 'samosa'],
  [/chaat|papdi|tikki|bhalla|bhalle/, 'chaat'],
  [/jalebi/, 'jalebi'],
  [/gulab jamun/, 'gulabjamun'],
  [/rasmalai|ras malai/, 'rasmalai'],
  [/phirni|firni/, 'phirni'],
  [/rabri|rabdi|malai makhan/, 'rabri'],
  [/halwa|halva|sheera|kesari/, 'halwa'],
  [/kulfi|falooda/, 'kulfi'],
  [/ice cream|sundae|scoop/, 'icecream'],
  [/mishti doi|shrikhand|basundi|ghevar|ghewar|malpua|mohanthal|kaju katli|peda/, 'mishti'],
  [/payasam|kheer/, 'payasam'],
  [/pizza/, 'pizza'],
  [/pasta|penne|alfredo|lasagna|spaghetti|arrabbiata|aglio|primavera|risotto/, 'pasta'],
  [/burger/, 'burger'],
  [/sandwich|club|croque|panini/, 'sandwich'],
  [/fries/, 'fries'],
  [/nachos/, 'nachos'],
  [/bruschetta/, 'bruschetta'],
  [/garlic bread|garlic toast|cheese toast|avocado toast|egg toast/, 'garlicbread'],
  [/wings|popcorn|lollipop/, 'wings'],
  [/momo|dumpling|gyoza|dim sum/, 'momo'],
  [/spring roll/, 'springroll'],
  [/noodles|ramen|pad thai|khow suey/, 'noodles'],
  [/fried rice/, 'friedrice'],
  [/chilli|manchurian|crispy corn|salt & pepper/, 'chilli'],
  [/soup/, 'soup'],
  [/salad/, 'salad'],
  [/hummus|pita/, 'hummus'],
  [/falafel/, 'falafel'],
  [/thali|baati|gatte|mess/, 'thali'],
  [/cold coffee|iced coffee|iced latte|cold brew|frappe/, 'coldcoffee'],
  [/coffee|latte|cappuccino|espresso|flat white|mocha/, 'coffee'],
  [/iced tea|lemon tea/, 'limesoda'],
  [/chai|tea|kulhad|sulaimani/, 'chai'],
  [/lassi|chaas|buttermilk|badam|rose milk|doodh/, 'lassi'],
  [/mojito|mocktail|cooler|blue lagoon|virgin/, 'mojito'],
  [/hot chocolate/, 'hotchocolate'],
  [/cold drink|soft drink|lime|lemonade|soda|sharbat|sherbet|shikanji|panna|jaljeera|coconut|nannari|water/, 'limesoda'],
  [/juice/, 'juice'],
  [/shake|smoothie|oreo/, 'shake'],
  [/brownie|fondant|lava/, 'brownie'],
  [/cheesecake/, 'cheesecake'],
  [/tiramisu/, 'tiramisu'],
  [/waffle/, 'waffle'],
  [/pancake/, 'pancake'],
  [/croissant|puff|bun maska|bun /, 'croissant'],
  [/cake|pastry|tart|pie|custard|biscuit|cookie|bread|rum ball|banana halwa/, 'cake'],
  [/prawn|shrimp/, 'prawn'],
  [/crab/, 'crab'],
  [/fish|karimeen|meen|pollichathu|calamari/, 'fish'],
  [/appam/, 'appam'],
  [/puttu/, 'puttu'],
  [/poha/, 'poha'],
  [/khichdi|khichri/, 'khichdi'],
  [/dhokla|khandvi|patra/, 'dhokla'],
  [/fafda|farsan/, 'fafda'],
  [/wine|sangria/, 'wine'],
  [/beer|pint/, 'beer'],
  [/cocktail|martini/, 'cocktail'],
  [/sizzler/, 'sizzler'],
  [/omelette|egg|bhurji/, 'omelette'],
  [/cutlet|croquette|patty|fry|pakoda|pakora/, 'cutlet'],
  [/curry|korma|rogan|stew|ishtu|salan|moilee|kadhai|nihari|saoji|sabzi|masala|oro|undhiyu|gravy|rassa/, 'curry'],
]

export const dishKey = (name) => {
  const n = ` ${String(name || '').toLowerCase()} `
  const hit = RULES.find(([re]) => re.test(n.trim()) || re.test(n))
  return hit ? hit[1] : ''
}
