/* Dish photos (src/assets/dishes/<key>.jpg): freely licensed Wikimedia Commons images, cropped and resized.
   They show the KIND of dish, not a specific venue's plate. Credits are listed in the app footer. */

export const DISH_PHOTO_CREDITS = {
  appam: { author: "Ranjithsiji", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Appam_Plate.JPG" },
  beer: { author: "Mitsjol", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:Alliantie_van_Biertapperijen_beer_glass.jpg" },
  biryani: { author: "Subhrajyoti07", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:A_home_made_plate_of_mutton_biryani_served_with_chicken_kassa_cooked_in_the_bengali_style.jpg" },
  brownie: { author: "JefferySAC", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Chocolate-brownie-hachatw.jpg" },
  bruschetta: { author: "Patrickfarrugia", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:A_typical_Maltese_bruschetta_with_fresh_Mediterranean_ingredients.jpg" },
  burger: { author: "Evan-Amos", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Big_Mac_hamburger.jpg" },
  butterchicken: { author: "stu_spivack", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Chicken_makhani.jpg" },
  cake: { author: "Daria YakovlevaMinor edits made by Subsidiary acco", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Piece_of_chocolate_cake_on_a_white_plate_decorated_with_chocolate_sauce.jpg" },
  chaat: { author: "Sonia Goyal", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Papdi-chaat.jpg" },
  chai: { author: "Ganesh Mohan T", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Masala_Chai.jpg" },
  cheesecake: { author: "Chris Gladis", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Cheesecake_with_blueberry_topping.jpg" },
  chilli: { author: "Marajozkee", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Chilly_Paneer_01.jpg" },
  chole: { author: "Gannu03", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Chole_Bhature_6.jpg" },
  cocktail: { author: "Ilikefood", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Brandy_flip_in_stemmed_cocktail_glass.jpg" },
  coffee: { author: "Vee Satayamas", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:A_cup_of_cappuccino.jpg" },
  coldcoffee: { author: "Tony Webster", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Iced_Coffee_in_Glass_-_Sunshine_Coffee_-_Laramie_Cafe_(53838344552).jpg" },
  crab: { author: "Dekcuf", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Chilli_crab-01.jpg" },
  croissant: { author: "Herry Wibisono (herryway)", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Croissants_au_beurre_(18953292873).jpg" },
  curry: { author: "Shukanto Das", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Chicken_Gravy_%22Jhol%22.jpg" },
  cutlet: { author: "dynamosquito from France", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Kotlet_(3119520131).jpg" },
  dahivada: { author: "Subhransuphotography", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Odia_Style_Dahi_bara_Puri_Odisha-IMG_953.jpg" },
  dal: { author: "Charles Haynes", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Dal_Makhani.jpg" },
  dhokla: { author: "Das Mousumi", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Dhokla_Home_Made,Duliajan,Assam.jpg" },
  dosa: { author: "Marajozkee", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Masala_dosa_01.jpg" },
  fafda: { author: "Drmoumitade", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Gujarati_breakfast_Fafda,Kadhi,Chatni,jalebi-Homemade-Gujarat-_pic_01.jpg" },
  falafel: { author: "Miansari66", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Falafel_1.JPG" },
  fish: { author: "Kalakki at Malayalam Wikipedia", license: "CC BY-SA 2.5", source: "https://commons.wikimedia.org/wiki/File:Meen_curry_2.JPG" },
  friedrice: { author: "Grendelkhan", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Pineapple_fried_rice_at_Banana_Leaf_in_Milpitas,_California.jpg" },
  fries: { author: "Chris Woodrich", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Cajun_fries_from_Popeyes_Louisiana_Kitchen,_Stratford,_Ontario,_2025-08-04.jpg" },
  garlicbread: { author: "Thriving Vegetarian", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Garlic_Toast_-_8420898886.jpg" },
  gulabjamun: { author: "Suyash.dwivedi", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Two_Gulab_Jamun_in_a_plate_01.jpg" },
  haleem: { author: "Nizzan Cohen", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:Haleem_02.jpg" },
  halwa: { author: "Dev Jadiya", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Moong_Dal_Halwa_and_Mysore_Pak_Sweet_Dish_Desert.jpg" },
  hotchocolate: { author: "KR Chrutti", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Hot_Chocolate.jpg" },
  hummus: { author: "Beyrouthhh at English Wikipedia", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:Lebanese_style_hummus.jpg" },
  icecream: { author: "Sam Howzit", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Strawberry_Ice_Cream_Sundae_(26853326174).jpg" },
  idli: { author: "Sutapa Pal", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Idli_Sambar-Noida-UP-SP004.jpg" },
  jalebi: { author: "PallaviKhale", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Jalebi_PK013.jpg" },
  juice: { author: "Agency of the United States Department of Agricult", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Orange_juice_1_edit1.jpg" },
  kachori: { author: "Rajeeb Dutta", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Kachori_MA23.jpg" },
  kebab: { author: "raasiel", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Seekh_Kebab.JPG" },
  kheema: { author: "Vidurmayor", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Keema_Pao_with_Hari_Chutney.jpg" },
  khichdi: { author: "Seena.ge", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Spicy_Khichdi.JPG" },
  kulfi: { author: "Gaurav Dhwaj Khadka", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Kulfi_3.jpg" },
  lassi: { author: "Gaurav Dhwaj Khadka", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Lassi_1.jpg" },
  limesoda: { author: "El Nuevo Doge", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Mojito,_Mazatl%C3%A1n,_30_de_noviembre_de_2022.jpg" },
  mishti: { author: "Kirti Poddar", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Mishti_Doi.jpg" },
  mojito: { author: "Alkemieug", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:MelissA_Mojito.jpg" },
  momo: { author: "TAPAS KUMAR HALDER", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Steamed_Momos_-_KOLKATA.jpg" },
  naan: { author: "Ganesh Mohan T", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Butter_Naan_2.jpg" },
  nachos: { author: "Navajcmer", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:The_Beanery_Nachos.jpg" },
  noodles: { author: "SGUae", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:Tasty_hakka_noodles_image.jpg" },
  omelette: { author: "Renee Comet (photographer)", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:FoodOmelete.jpg" },
  pancake: { author: "Mae Mu", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg" },
  paneer: { author: "Sonja Pauen -Stanhopea", license: "CC BY 2.0 de", source: "https://commons.wikimedia.org/wiki/File:Panir_Tikka_Indian_cheese_grilled.jpg" },
  panipuri: { author: "Teena Sometimes", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Crispy_Pani_Puri.jpg" },
  paratha: { author: "Gannu03", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Aloo_Paratha_(96238).jpg" },
  pasta: { author: "Rocky Masum This work was made by Masum-al-Hasan R", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:A_plate_of_red_sauce_pasta.jpg" },
  pavbhaji: { author: "Solowomanwalks", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Pav_bhaji_SWW.jpg" },
  payasam: { author: "Ayshamarjana", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Kheer_(Payasam).jpg" },
  phirni: { author: "Anwesha394", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Phirni_at_Cool_Point,_Chandni_Chawk.jpg" },
  pizza: { author: "Mario56", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Margherita_Originale.JPG" },
  poha: { author: "Mrsagar105", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Poha_with_tomato_sause.jpg" },
  prawn: { author: "Jubair1985", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Bangladeshi_Prawn_Curry.jpg" },
  puttu: { author: "Mathew Jibin", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Puttu_(Rice_Flour_steamed_cake).jpg" },
  rabri: { author: "Ravi Talwar", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Homemade_Rabri.jpg" },
  rasmalai: { author: "Miansari66", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Ras_Malai.JPG" },
  salad: { author: "Paasikivi", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Greek_salad_and_Tzatziki.jpg" },
  samosa: { author: "Swathi sri srinivasa raghavan", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Samosa_with_sweet_chutney.jpg" },
  sandwich: { author: "jeffreyw", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Grilled_cheese_sandwich_with_roasted_tomato_soup.jpg" },
  shake: { author: "Vyacheslav Argenberg", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:San_Vicente,_Milkshake,_Palawan,_Philippines.jpg" },
  sizzler: { author: "Mark James Miller", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Sizzler,_steak_and_lobster.jpg" },
  soup: { author: "JIP", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Tomato_soup,_rye_bread_and_white_wine.jpg" },
  springroll: { author: "Srujanabotcha", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Golden_Vegetable_Spring_Rolls_Served_with_Dipping_Sauce.jpg" },
  thali: { author: "Vyacheslav Argenberg", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:Darjeeling,_India,_Indian_Thali_meal.jpg" },
  tiramisu: { author: "Sharon Chen from Austin, United States", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Classic_Italian_Tiramisu-3_(29989504485).jpg" },
  vada: { author: "Sugeesh at ml.wikipedia", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:%E0%B4%89%E0%B4%B4%E0%B5%81%E0%B4%A8%E0%B5%8D%E0%B4%A8%E0%B5%81%E0%B4%B5%E0%B4%9F%E0%B4%95%E0%B5%BE.JPG" },
  vadapav: { author: "Sharvarism", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Crunchy_Crispy_Vada_pav.jpg" },
  waffle: { author: "Ralph Daily", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Waffle_with_strawberries_and_confectioner%27s_sugar.jpg" },
  wine: { author: "André Karwath", license: "CC BY-SA 2.5", source: "https://commons.wikimedia.org/wiki/File:Red_and_white_wine_in_glass.jpg" },
  wings: { author: "Paul Lowry", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:Chicken_Wings-_It%27s_been_a_while._Baton_Rouge_LA_2026.jpg" },
  wrap: { author: "Vivekpat30", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Chicken-kathi-roll-recipe.jpg" },
}
