/* Photo credits for src/assets/venues/*.jpg. Photos are from Wikimedia Commons, used under their licences.
   CC BY / CC BY-SA require crediting the author (shown under each photo in the app). All photos are illustrative:
   they show the place, dish or mood, not necessarily the exact venue. To use your own photo, replace the .jpg file
   and update (or delete) its entry here. Images were cropped and resized. */

export const PHOTO_CREDITS = {
  za: { note: "Noor-Us-Sabah Palace, the heritage hotel that houses Za-aiqa", author: "BijuJohn", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:NoorUsSabahPalaceHeritageHotel-Bhopal.jpg" },
  umt: { note: "A candlelit table setting (another restaurant)", author: "PattayaPatrol", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:DZ6_2628_Cozy_candlelit_dinner_for_two_elegant_Thai_restaurant_setting_with_twinkling_lights_and_a_delicate_orchid_centerpiece.jpg" },
  ww: { note: "Sunset over the Upper Lake, Bhopal", author: "SUBHASH E", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Sunset_in_Upper_lake,_Bhopal.jpg" },
  jnp: { note: "Noor-Us-Sabah Palace, another heritage hotel in Bhopal", author: "BijuJohn", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:NoorUsSabahPalaceHeritageHotel-Bhopal.jpg" },
  oliver: { note: "A cozy café corner (another café)", author: "Kavig624", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Cafe_Interior_with_Coffee.jpg" },
  ich: { note: "An Indian Coffee House outlet (not the Bhopal branch)", author: "Ganesh Mohan T", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Indian_Coffee_House_01.jpg" },
  gfb: { note: "A Greek salad (illustrative)", author: "Armineaghayan", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Greek_Salad_from_Thessaloniki.jpg" },
  bn: { note: "A Barbeque Nation table grill (another city's outlet)", author: "Kritzolina", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Skewers_at_Barbeque_Nation_01.jpg" },
  sg: { note: "Papri chaat, a street-food favourite (illustrative)", author: "Biswarup Ganguly", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:Papri_Chaat_-_Alipore_-_Kolkata_2013-02-10_4941.JPG" },
  md: { note: "Jalebis being fried at a sweet shop (illustrative)", author: "Billjones94", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Jalebis_are_being_fried_at_a_local_sweet_shop_4.jpg" },
  "in-sarafa": { real: true, note: "Street food at Sarafa Bazaar, Indore", author: "आर्या जोशी", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Sarafa_Bajar_street_food.jpg" },
  "in-chappan": { real: true, note: "Sweets and snacks at Chappan Dukan, Indore", author: "आर्या जोशी", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Chappan_Dukan_street_Food.jpg" },
  "ah-manek": { real: true, note: "Manek Chowk night food market, Ahmedabad", author: "Pravega", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Manek_Chowk_(Ahmedabad)_01.jpg" },
  "lk-tunday": { real: true, note: "The Tunday Kababi signboard, Lucknow", author: "Matt Stabile", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Tunday_Kebabi,_Lucknow.jpg" },
  "dl-kar": { note: "Nihari at Karim's, Jama Masjid, Old Delhi", real: true, author: "Kxnyshk", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Nihari_at_Karim%27s_(Jama_Masjid,_Old_Delhi).png" },
  "dl-paranthe": { note: "Dal parantha from Paranthe Wali Gali, Chandni Chowk", real: true, author: "Ravi Dwivedi", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Dal_Parantha_from_Paranthe_Wali_Gali,_Chandni_Chowk,_India.jpg" },
  "dl-ich": { note: "Indian Coffee House, Connaught Place", real: true, author: "Kishy-edits", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Indian_Coffee_House_at_Connaught_Place.jpg" },
  "dl-farzi": { note: "A dessert at Farzi Café", real: true, author: "Umair Abbasi from Schaumburg, United States", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Farzi_Caf%C3%A9_(34125491971).jpg" },
  "dl-smoke": { note: "Fries at Smoke House Deli, Khan Market", real: true, author: "Hans Vivek rickyzden", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Smoke_House_Deli,_Khan_Market,_India_(Unsplash).jpg" },
  "mb-mondegar": { note: "The table at Cafe Mondegar, Colaba", real: true, author: "Prof tpms", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Cafe_Mondegar,_Colaba,_Mumbai_(2).jpg" },
  "mb-bademiya": { note: "Bademiya at night, Colaba", real: true, author: "Benjamin Vander Steen from Victoria, Canada", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Bademiya_restaurant,_Mumbai.jpg" },
  "mb-madras": { note: "Cafe Madras, Matunga", real: true, author: "Cafe Madras", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Cafe_Madras_Entrance.jpg" },
  "mb-leo": { note: "Inside Leopold Cafe, Colaba", real: true, author: "Adam Jones from Kelowna, BC, Canada", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Interior_of_Leopold_Cafe_-_Colaba_District_-_Mumbai_-_Maharashtra_-_India_(25787484134).jpg" },
  "mb-brit": { note: "Britannia & Co., Ballard Estate", real: true, author: "Kanad Sanyal", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Britannia_and_Co.jpg" },
  "bl-mtr": { note: "Mavalli Tiffin Rooms, Lalbagh Road", real: true, author: "Gpkp", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Mavalli_Tiffin_Room_(6),_Lalbagh_Road,_Bengaluru.jpg" },
  "bl-koshys": { note: "Koshy's, St Marks Road", real: true, author: "Atr hugo", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Koshys.jpg" },
  "bl-brahmins": { note: "Idli-vada at Brahmin's Coffee Bar", real: true, author: "Maharana7573", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Brahmin%27s_Coffee_Bar_Idli_Vada.jpg" },
  "bl-vid": { note: "Masala dosa at Vidyarthi Bhavan", real: true, author: "Maharana7573", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Vidyarthi_Bhavan_Masala_Dosa.jpg" },
  "hy-bawarchi": { note: "Bawarchi, RTC X Roads", real: true, author: "Adbh266", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:RTC_x_roads_Bawarchi.jpg" },
  "hy-karachi": { note: "Karachi Bakery", real: true, author: "Adbh266", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Karachi_bakery_.jpg" },
  "hy-pista": { note: "Pista House", real: true, author: "Bssasidhar", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:Pista_House_Kondapur_(21_Aug_2019).jpg" },
  "hy-niloufer": { note: "Irani chai and bun maska at Cafe Niloufer", real: true, author: "PJeganathan", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Tea_and_Bun_Muska_from_Cafe_Niloufer_Hyderabad_JEG_IMG_20260829_112104521.jpg" },
  "hy-par": { note: "Osmania biscuits at Paradise", real: true, author: "Divya4232", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Osmania_biscuits_-_Paradise_Biryani,_Mahatma_Gandhi_Rd,_Sappu_Bagh_Apaprtment,_Jogani,_Ramgopalpet,_Secunderabad_-_Hyderabad_-_DSC_0031.jpg" },
  "ch-a2b": { note: "A2B – Adyar Ananda Bhavan", real: true, author: "Helppublic", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Adyar_Ananda_Bhavan.jpg" },
  "ch-mur": { note: "Ghee podi idli at Murugan Idli Shop", real: true, author: "Harikrishnan N", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Ghee_Podi_Idli_-_Murugan_Idli_Shop,_Chennai_-_TamilNadu_-_PXL0246.jpg" },
  "kl-arsalan": { note: "Arsalan, Circus Avenue", real: true, author: "Biswarup Ganguly", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:Arsalan_Restaurant_-_28_Circus_Avenue_-_Kolkata_20170825180854.jpg" },
  "kl-aminia": { note: "Mutton biryani at Aminia", real: true, author: "Debasree1983", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Mutton_Biriyani_-_Aminia_Restaurant-_Kolkata_-_West_Bengal_-_015.jpg" },
  "kl-flu": { note: "Flury's, Park Street", real: true, author: "Pechristener", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Flurys,_Park_Street,_Kolkata,_Street_View.jpg" },
  "kl-pc": { note: "Chelo kebab at Peter Cat", real: true, author: "Boby Ortain", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Chelow_Kabab,_Peter_Cat,_Park_Street,_Kolkata,_West_Bengal,_IMG_20210410_131018800.jpg" },
  "kl-ich": { note: "Indian Coffee House, College Street", real: true, author: "খাঁ শুভেন্দু", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Indian_Coffee_House_(Kolkata-College_Street_Coffee_House)_WP_20171224_10_45_27_Pro.jpg" },
  "kl-paramount": { note: "Paramount Sherbet, College Street", real: true, author: "Deejayrocks2", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Paramount_Sherbet_college_street_kolkata_west_bengal_04.jpg" },
  "pn-kayani": { note: "Kayani Bakery, East Street", real: true, author: "Miteshbhodia", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Kayani_bakery.JPG" },
  "pn-goodluck": { note: "Cafe Goodluck, Deccan", real: true, author: "Djknusper", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Coffee_Good_Luck_in_Pune_(2025).jpg" },
  "pn-roopali": { note: "Roopali, FC Road", real: true, author: "Spandanbhatt94", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Roopali_Restaurant,_FC_Road.JPG" },
  "pn-gb": { note: "German Bakery, Koregaon Park", real: true, author: "KevinScott.Org", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:German_Bakery_Pune.jpg" },
  "ah-gordhan": { note: "A thali at Gordhan Thal", real: true, author: "Nupur73", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Gordhan_Thal.jpg" },
  "jp-lassi": { note: "Lassi at Shreenath Lassiwala", real: true, author: "Chainwit.", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Shreenath_Lassiwala_Jaipur_(2022)_-_img_04.jpg" },
  "cd-pal": { note: "Pal Dhaba, Sector 28", real: true, author: "shankar s. from Poona (pune), India, India", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Pal_Dhaba-_a_legendary_Chandigarh_institution_(44272499961).jpg" },
}
