/* Many more real venues for every city, including Jain food. Names are real places found via web searches;
   menus are illustrative templates (see quick.js). Row: [city, kind, id, name, vibe, emoji, menu type, tagline, price scale] */
import { quick } from './quick'

const ROWS = [
  /* ------------------------------- Mumbai ------------------------------- */
  ['mumbai', 'restaurant', 'mb-trishna', 'Trishna', 'Romantic', '🦀', 'fine', 'Famed Fort seafood, known for butter-garlic crab.', 1.9],
  ['mumbai', 'restaurant', 'mb-khyber', 'Khyber', 'Romantic', '🕌', 'fine', 'Elegant North Indian dining with kebabs, biryanis and curries.', 1.8],
  ['mumbai', 'restaurant', 'mb-americano', 'Americano', 'Vibrant', '🍕', 'pub', 'A hip Kala Ghoda spot for pizza, handmade pasta and tiramisu.', 1.5],
  ['mumbai', 'street', 'mb-bademiya', 'Bademiya', 'Casual', '🍢', 'nonveg', 'The late-night Colaba kebab stop, open until the early hours.', 0.85],
  ['mumbai', 'restaurant', 'mb-mondegar', 'Cafe Mondegar', 'Vibrant', '🎵', 'pub', 'Quirky decor, a jukebox and a lively Colaba crowd.', 0.95],
  ['mumbai', 'restaurant', 'mb-canteen', 'The Bombay Canteen', 'Romantic', '🥂', 'fine', 'Playful, modern Indian cooking in Lower Parel.', 1.7],
  ['mumbai', 'restaurant', 'mb-swati', 'Swati Snacks', 'Casual', '🥘', 'veg', 'Gujarati street food and snacks, loved by locals and visitors.', 1.1],
  ['mumbai', 'cafe', 'mb-theobroma', 'Theobroma', 'Cozy', '🍰', 'cafe', 'A bakery-café famous for brownies, cakes and coffee.', 1.1],
  ['mumbai', 'cafe', 'mb-kyani', 'Kyani & Co.', 'Cozy', '🫖', 'cafe', 'An old Irani café: bun maska, chai and caramel custard.', 0.8],
  ['mumbai', 'restaurant', 'mb-madras', 'Cafe Madras', 'Casual', '🥞', 'south', 'A Matunga classic for idli, dosa and filter coffee.', 0.9],
  ['mumbai', 'street', 'mb-sardar', 'Sardar Pav Bhaji', 'Casual', '🍞', 'chaat', 'The Tardeo pav bhaji everyone talks about.', 1],
  ['mumbai', 'restaurant', 'mb-social', 'Social (Mumbai)', 'Vibrant', '🎧', 'pub', 'A buzzing café-bar hangout.', 1.2],
  ['mumbai', 'restaurant', 'mb-jainsabkuch', 'Jain Sabkuchh Food Plaza (Malad)', 'Casual', '🥪', 'jain', 'Jain chaat, sandwiches, burgers, South Indian and pav bhaji.', 0.9],
  ['mumbai', 'restaurant', 'mb-samrat', 'Samrat Restaurant (Churchgate)', 'Cozy', '🍛', 'jain', 'Long-time Jain favourite, known for Jain pav bhaji and dal khichdi.', 1.1],
  ['mumbai', 'restaurant', 'mb-relish', 'Relish (Churchgate)', 'Cozy', '🥗', 'jain', 'Gujarati thali plus Italian and Mexican Jain dishes.', 1.2],
  ['mumbai', 'restaurant', 'mb-allinone', 'All In One – Pure Jain', 'Casual', '🍕', 'jain', 'Jain food in fancy cuisines like Mexican and Italian.', 1],
  ['mumbai', 'restaurant', 'mb-indigodeli', 'Indigo Deli (Jain menu)', 'Cozy', '🍕', 'jain', 'Chic deli known for Jain pizzas and a Jain menu.', 1.6],
  ['mumbai', 'restaurant', 'mb-naminath', 'Naminath Jain Bhojanshala', 'Casual', '🍲', 'jain', 'A pure-veg Jain bhojanshala near Mumbai Central.', 0.8],

  /* ------------------------------ Bengaluru ----------------------------- */
  ['bengaluru', 'cafe', 'bl-thirdwave', 'Third Wave Coffee Roasters', 'Cozy', '☕', 'cafe', 'Artisanal brews and cold brews in Indiranagar.', 1.2],
  ['bengaluru', 'cafe', 'bl-bcs', 'Bangalore Coffee Shop', 'Cozy', '🥐', 'cafe', 'Espresso, sandwiches and pastries in Indiranagar.', 1.2],
  ['bengaluru', 'cafe', 'bl-yogisthaan', 'Yogisthaan', 'Cozy', '🌿', 'cafe', 'A bungalow garden café with a health-minded menu.', 1.1],
  ['bengaluru', 'restaurant', 'bl-tayyabs', 'Tayyabs (Indiranagar)', 'Casual', '🌯', 'nonveg', 'A cosy spot for rolls, kebabs and beda rotis.', 1],
  ['bengaluru', 'cafe', 'bl-truffles', 'Truffles', 'Vibrant', '🍔', 'cafe', 'Koramangala favourite for burgers, Italian and desserts.', 1.1],
  ['bengaluru', 'restaurant', 'bl-chianti', 'Chianti', 'Romantic', '🍝', 'fine', 'Italian dining in Koramangala, loved for its cannelloni.', 1.1],
  ['bengaluru', 'restaurant', 'bl-mtr', 'Mavalli Tiffin Rooms (MTR)', 'Casual', '🥘', 'south', 'A century-old Bengaluru breakfast institution.', 1.1],
  ['bengaluru', 'restaurant', 'bl-ctr', 'Central Tiffin Room (CTR)', 'Casual', '🧈', 'south', 'Malleshwaram’s famous benne masala dosa.', 0.9],
  ['bengaluru', 'restaurant', 'bl-windmills', 'Windmills Craftworks', 'Vibrant', '🎷', 'pub', 'Craft beer, live music and a big menu.', 1.4],
  ['bengaluru', 'restaurant', 'bl-churchsocial', 'Church Street Social', 'Vibrant', '🎧', 'pub', 'A lively Church Street café-bar.', 1.2],
  ['bengaluru', 'cafe', 'bl-bluetokai', 'Blue Tokai Coffee Roasters', 'Cozy', '☕', 'cafe', 'Specialty coffee roasted in India.', 1.1],
  ['bengaluru', 'cafe', 'bl-smokehouse', 'Smoke House Deli (Bengaluru)', 'Cozy', '🥓', 'cafe', 'An all-day deli café.', 1.5],
  ['bengaluru', 'restaurant', 'bl-empire', 'Empire Restaurant', 'Casual', '🍗', 'nonveg', 'Late-night kebabs, biryani and ghee rice.', 1],
  ['bengaluru', 'cafe', 'bl-koshys', 'Koshy’s', 'Cozy', '☕', 'cafe', 'A classic St Marks Road café with old-world charm.', 1.1],
  ['bengaluru', 'restaurant', 'bl-brahmins', 'Brahmin’s Coffee Bar', 'Casual', '🍩', 'south', 'A tiny Basavanagudi spot for idli-vada and filter coffee.', 0.6],
  ['bengaluru', 'restaurant', 'bl-meghana', 'Meghana Foods', 'Casual', '🍛', 'nonveg', 'Andhra-style biryani, loved across Bengaluru.', 1.1],
  ['bengaluru', 'restaurant', 'bl-higher', 'The Higher Taste (ISKCON)', 'Cozy', '🪷', 'jain', 'Pure vegetarian dining with Jain options at the ISKCON complex.', 1],
  ['bengaluru', 'restaurant', 'bl-sante', 'Sante Spa Cuisine (Jayanagar)', 'Romantic', '🥗', 'jain', 'Wellness-minded vegetarian dining with Jain-friendly dishes.', 2],

  /* ------------------------------ Hyderabad ----------------------------- */
  ['hyderabad', 'restaurant', 'hy-bahar', 'Cafe Bahar', 'Casual', '🍚', 'nonveg', 'Basheerbagh biryani and haleem since 1973.', 0.9],
  ['hyderabad', 'restaurant', 'hy-shah', 'Shah Ghouse Cafe & Restaurant', 'Casual', '🍖', 'nonveg', 'Old City biryani, haleem and juicy kebabs.', 0.85],
  ['hyderabad', 'restaurant', 'hy-bawarchi', 'Bawarchi', 'Casual', '🍛', 'nonveg', 'RTC X Roads, famous for kachi gosht ki biryani.', 0.9],
  ['hyderabad', 'restaurant', 'hy-chutneys', 'Chutneys', 'Casual', '🥥', 'south', 'Six chutneys with dosas, idlis and pesarattu.', 1],
  ['hyderabad', 'cafe', 'hy-flurys', 'Flurys (Banjara Hills)', 'Cozy', '🧁', 'cafe', 'Pastries and tea in Banjara Hills.', 1.2],
  ['hyderabad', 'cafe', 'hy-habitat', 'Habitat Cafe', 'Cozy', '🌿', 'cafe', 'A Banjara Hills café for coffee and light meals.', 1.1],
  ['hyderabad', 'cafe', 'hy-gallery', 'The Gallery Cafe', 'Cozy', '🖼️', 'cafe', 'A relaxed Banjara Hills café.', 1.1],
  ['hyderabad', 'cafe', 'hy-roastery', 'The Roastery Coffee House', 'Cozy', '☕', 'cafe', 'Freshly brewed coffee loved by coffee connoisseurs.', 1.2],
  ['hyderabad', 'cafe', 'hy-concu', 'Conçu', 'Romantic', '🥐', 'cafe', 'A Parisian-style café in Jubilee Hills.', 1.5],
  ['hyderabad', 'restaurant', 'hy-telangana', 'Telangana Spice Kitchen Bar & Grill', 'Vibrant', '🌶️', 'north', 'Telangana flavours with a bar and grill.', 1.3],
  ['hyderabad', 'cafe', 'hy-belposto', 'Bel Posto The Cafe', 'Cozy', '🍝', 'cafe', 'A Road No. 36 café for Italian plates.', 1.3],
  ['hyderabad', 'cafe', 'hy-karachi', 'Karachi Bakery', 'Casual', '🍪', 'cafe', 'Famous for fruit biscuits and bakery treats.', 0.8],
  ['hyderabad', 'street', 'hy-pista', 'Pista House', 'Casual', '🥣', 'nonveg', 'Haleem, biryani and bakery treats.', 0.8],
  ['hyderabad', 'cafe', 'hy-niloufer', 'Cafe Niloufer', 'Casual', '🍞', 'cafe', 'Irani chai and bun maska.', 0.6],
  ['hyderabad', 'restaurant', 'hy-ohris', 'Ohri’s', 'Vibrant', '🎉', 'north', 'A big, buzzy multi-cuisine restaurant group.', 1.4],
  ['hyderabad', 'restaurant', 'hy-bn', 'Barbeque Nation (Hyderabad)', 'Vibrant', '🔥', 'bbq', 'Live grills at your table.', 1],

  /* ------------------------------- Chennai ------------------------------ */
  ['chennai', 'restaurant', 'ch-saravana', 'Saravana Bhavan (Chennai)', 'Casual', '🥞', 'south', 'The vegetarian South Indian chain, from its home city.', 1.1],
  ['chennai', 'restaurant', 'ch-rathna', 'Rathna Cafe', 'Casual', '🥘', 'south', 'Mylapore-Triplicane idli-sambar classic.', 0.8],
  ['chennai', 'cafe', 'ch-qua', 'Qua', 'Cozy', '🍝', 'cafe', 'A Besant Nagar café with Continental and Italian plates.', 1.2],
  ['chennai', 'restaurant', 'ch-rasanai', 'Rasanai', 'Cozy', '🌴', 'south', 'South Indian dishes near Elliot’s Beach.', 1.2],
  ['chennai', 'cafe', 'ch-littleitaly', 'Little Italy', 'Cozy', '🍕', 'cafe', 'Coffee, Italian, Mexican and bakery items.', 1.2],
  ['chennai', 'cafe', 'ch-filli', 'FiLLi Cafe', 'Cozy', '🥐', 'cafe', 'A bakery-café chain across the city.', 1],
  ['chennai', 'cafe', 'ch-tummy', 'Tummy Tales', 'Cozy', '🍰', 'cafe', 'Desserts and Continental plates.', 1],
  ['chennai', 'restaurant', 'ch-a2b', 'A2B – Adyar Ananda Bhavan', 'Casual', '🍮', 'south', 'Vegetarian meals and Tamil sweets.', 0.9],
  ['chennai', 'restaurant', 'ch-kaidi', 'Kaidi Kitchen', 'Casual', '🍛', 'veg', 'A Mylapore vegetarian restaurant.', 1],
  ['chennai', 'cafe', 'ch-novelty', 'Novelty Tea House', 'Casual', '🍵', 'cafe', 'A Mylapore tea house.', 0.7],
  ['chennai', 'restaurant', 'ch-rayars', 'Rayar’s Mess', 'Casual', '🥞', 'veg', 'A Mylapore breakfast institution.', 0.6],
  ['chennai', 'restaurant', 'ch-viswanathan', 'Viswanathan Chettinadu Hotel', 'Casual', '🍗', 'nonveg', 'Chettinad non-vegetarian meals in Mylapore.', 1],
  ['chennai', 'restaurant', 'ch-kaaraikudi', 'Kaaraikudi Chettinad Restaurant', 'Casual', '🌶️', 'nonveg', 'Chettinad cooking in Mylapore.', 1.1],
  ['chennai', 'cafe', 'ch-madbean', 'Mad Bean Cafe and Roastery', 'Cozy', '🫘', 'cafe', 'A Mylapore café and coffee roastery.', 1.1],
  ['chennai', 'cafe', 'ch-ccd', 'Café Coffee Day (Mylapore)', 'Cozy', '☕', 'cafe', 'A familiar café for coffee and bites.', 1],

  /* ------------------------------- Kolkata ------------------------------ */
  ['kolkata', 'restaurant', 'kl-barbq', 'Bar-B-Q (Park Street)', 'Romantic', '🍷', 'fine', 'Vintage décor across three buildings, with Indian and Chinese sections.', 1.3],
  ['kolkata', 'restaurant', 'kl-kewpies', 'Kewpie’s', 'Cozy', '🐟', 'nonveg', 'Authentic and affordable Bengali dishes.', 1],
  ['kolkata', 'restaurant', 'kl-arsalan', 'Arsalan', 'Casual', '🍚', 'nonveg', 'Mughlai food with a famous biryani.', 1],
  ['kolkata', 'restaurant', 'kl-ohc', 'Oh! Calcutta', 'Romantic', '🦐', 'fine', 'Modern Bengali classics like daab chingri and bhapa ilish.', 1.8],
  ['kolkata', 'street', 'kl-nizams', 'Nizam’s (New Market)', 'Casual', '🌯', 'nonveg', 'Said to be the first to serve kathi rolls in Kolkata.', 0.8],
  ['kolkata', 'restaurant', 'kl-aminia', 'Aminia', 'Casual', '🍛', 'nonveg', 'Mutton biryani and Mughlai classics.', 0.9],
  ['kolkata', 'restaurant', 'kl-royal', 'Royal Indian Hotel', 'Casual', '🍖', 'nonveg', 'A Chitpur institution for biryani and kebabs.', 0.9],
  ['kolkata', 'restaurant', 'kl-balwant', 'Balwant Singh’s Eating House', 'Casual', '🍛', 'north', 'A no-frills Punjabi eatery.', 0.8],
  ['kolkata', 'cafe', 'kl-paramount', 'Paramount Sherbet', 'Casual', '🥤', 'cafe', 'A College Street sherbet and snack shop.', 0.5],

  /* --------------------------------- Pune -------------------------------- */
  ['pune', 'restaurant', 'pn-roopali', 'Roopali (FC Road)', 'Casual', '🥞', 'south', 'One of FC Road’s legendary South Indian restaurants.', 1.1],
  ['pune', 'restaurant', 'pn-wadeshwar', 'Wadeshwar', 'Casual', '🥘', 'south', 'FC Road’s long-loved eatery for South Indian and Maharashtrian food.', 0.9],
  ['pune', 'cafe', 'pn-goodluck', 'Cafe Goodluck', 'Cozy', '☕', 'cafe', 'An Irani café since 1935: chai, bun maska, bun omelette.', 0.8],
  ['pune', 'cafe', 'pn-kayani', 'Kayani Bakery', 'Casual', '🍪', 'cafe', 'Famous Shrewsbury biscuits and mawa cakes since 1955.', 0.6],
  ['pune', 'cafe', 'pn-dorab', 'Dorabjee & Sons', 'Casual', '🥧', 'cafe', 'A classic Parsi eatery in Camp.', 0.9],
  ['pune', 'cafe', 'pn-marzorin', 'Marz-O-Rin', 'Casual', '🍨', 'cafe', 'A heritage Pune café for sandwiches and desserts.', 0.9],
  ['pune', 'restaurant', 'pn-shabree', 'Shabree', 'Casual', '🍛', 'veg', 'A Maharashtrian thali favourite.', 1],
  ['pune', 'restaurant', 'pn-shreyas', 'Hotel Shreyas', 'Casual', '🍲', 'veg', 'Known for its traditional Maharashtrian thali.', 1],

  /* ------------------------------ Ahmedabad ----------------------------- */
  ['ahmedabad', 'restaurant', 'ah-gordhan', 'Gordhan Thal', 'Casual', '🍽️', 'veg', 'Family-style Gujarati thali in Satellite.', 1],
  ['ahmedabad', 'restaurant', 'ah-swati', 'Swati Snacks (Law Garden)', 'Casual', '🥘', 'veg', 'Authentic Gujarati snacks and street food.', 1],
  ['ahmedabad', 'restaurant', 'ah-rajwadu', 'Rajwadu', 'Cozy', '🏺', 'veg', 'A Vejalpur restaurant for Gujarati meals, desserts and coffee.', 1.2],
  ['ahmedabad', 'cafe', 'ah-mocha', 'Cafe Mocha (C G Road)', 'Cozy', '🪵', 'cafe', 'A cozy café with rustic wooden furniture and warm lighting.', 1],
  ['ahmedabad', 'restaurant', 'ah-mirch', 'Mirch Masala', 'Vibrant', '🌶️', 'north', 'Ahmedabad’s first theme restaurant.', 1.2],
  ['ahmedabad', 'cafe', 'ah-creamoholic', 'Creamoholic Café & Resto', 'Cozy', '🍦', 'cafe', 'A popular café near Law Garden.', 1],
  ['ahmedabad', 'cafe', 'ah-williamjohns', 'William John’s Pizza', 'Vibrant', '🍕', 'cafe', 'A pizza-first café.', 1],
  ['ahmedabad', 'cafe', 'ah-lucky', 'Lucky Restaurant', 'Cozy', '🍵', 'cafe', 'A famous tea stop in an unusual setting.', 0.6],
  ['ahmedabad', 'street', 'ah-jagdish', 'Jagdish Farsan Mart', 'Casual', '🥨', 'sweets', 'Gujarati farsan and sweets.', 0.7],

  /* -------------------------------- Jaipur ------------------------------ */
  ['jaipur', 'restaurant', 'jp-niros', 'Niro’s', 'Casual', '🥘', 'north', 'A long-time MI Road favourite since 1949, loved for its gatte ki sabzi.', 1.2],
  ['jaipur', 'restaurant', 'jp-spicecourt', 'Spice Court (Jacob Road)', 'Vibrant', '🌶️', 'north', 'Some of the spiciest Rajasthani dishes.', 1.1],
  ['jaipur', 'restaurant', 'jp-chokhi', 'Chokhi Dhani', 'Vibrant', '🎪', 'veg', 'A village-fair-style Rajasthani thali experience outside the city.', 1.6],
  ['jaipur', 'restaurant', 'jp-peacock', 'Peacock Rooftop Restaurant', 'Casual', '🦚', 'north', 'A multi-level rooftop at Hotel Pearl Palace.', 0.9],
  ['jaipur', 'restaurant', 'jp-handi', 'Handi Restaurant', 'Casual', '🍲', 'nonveg', 'North Indian curries and kebabs.', 1],
  ['jaipur', 'restaurant', 'jp-suvarna', 'Suvarna Mahal (Rambagh Palace)', 'Romantic', '👑', 'fine', 'Royal dining at Rambagh Palace.', 3],
  ['jaipur', 'restaurant', 'jp-palladio', 'Bar Palladio', 'Romantic', '🍸', 'pub', 'A glamorous Italian-style bar and café.', 2],
  ['jaipur', 'street', 'jp-lassi', 'Shreenath Lassiwala (MI Road)', 'Casual', '🥛', 'sweets', 'Thick lassi in terracotta cups.', 0.5],

  /* ------------------------------- Lucknow ------------------------------ */
  ['lucknow', 'restaurant', 'lk-wahid', 'Wahid Biryani', 'Casual', '🍚', 'nonveg', 'Aminabad dum biryani, serving since 1955.', 0.9],
  ['lucknow', 'street', 'lk-prakash', 'Prakash Kulfi', 'Casual', '🍨', 'sweets', 'The famous Aminabad kulfi.', 0.6],
  ['lucknow', 'restaurant', 'lk-naush', 'Naushijaan', 'Casual', '🍢', 'nonveg', 'Kebabs and Lucknowi biryani.', 1],
  ['lucknow', 'restaurant', 'lk-moti', 'Moti Mahal (Lucknow)', 'Casual', '🍯', 'veg', 'Pure-desi-ghee poori breakfasts, sweets and chaat.', 1],
  ['lucknow', 'cafe', 'lk-hons', 'Hons – All Day Dining', 'Cozy', '🥞', 'cafe', 'All-day dining in Hazratganj.', 1.1],
  ['lucknow', 'cafe', 'lk-haloz', 'Haloz Cafe', 'Cozy', '☕', 'cafe', 'A highly rated Hazratganj café.', 1],
  ['lucknow', 'cafe', 'lk-choco', 'The Chocolate Room', 'Cozy', '🍫', 'cafe', 'A dessert café in Hazratganj.', 1.1],
  ['lucknow', 'cafe', 'lk-truccos', 'Truccos', 'Cozy', '🍔', 'cafe', 'A Hazratganj café.', 1.2],
  ['lucknow', 'cafe', 'lk-mantar', 'Mantar', 'Cozy', '🥗', 'cafe', 'A Hazratganj café.', 1],
  ['lucknow', 'cafe', 'lk-buttercup', 'Buttercup Bungalow', 'Cozy', '🧁', 'cafe', 'An artisan bakery and deli in Gomti Nagar.', 1.2],
  ['lucknow', 'cafe', 'lk-nosugar', 'Cafe Hons – House of No Sugar', 'Cozy', '🍵', 'cafe', 'A sugar-free menu made with stevia.', 1.1],
  ['lucknow', 'cafe', 'lk-capoor', 'Capoor & Sons', 'Cozy', '🥐', 'cafe', 'An all-in-one café, restaurant and bakery.', 1.2],
  ['lucknow', 'restaurant', 'lk-mochabar', 'Mocha Cafe & Bar', 'Vibrant', '🍕', 'pub', 'A Gomti Nagar rooftop café with customisable pasta and pizza.', 1.1],
  ['lucknow', 'restaurant', 'lk-montana', 'Montana Cafe and Lounge', 'Romantic', '🌃', 'pub', 'Often called the best rooftop café in Gomti Nagar.', 1.2],

  /* ------------------------------ Chandigarh ---------------------------- */
  ['chandigarh', 'restaurant', 'cd-flavours', 'Flavours', 'Casual', '🍛', 'north', 'Sector 17: biryani, Chinese, Italian and North Indian.', 1.2],
  ['chandigarh', 'cafe', 'cd-b2s', 'Back To Source', 'Cozy', '🥗', 'cafe', 'Sector 17: desserts, fast food and Continental.', 1],
  ['chandigarh', 'cafe', 'cd-winnis', 'Winnis Resto Bar', 'Vibrant', '🥂', 'cafe', 'A Sector 17 bakery and bar.', 1],
  ['chandigarh', 'restaurant', 'cd-space', 'Space', 'Vibrant', '🚀', 'nonveg', 'Mughlai, North Indian and kebabs in Sector 17.', 1.3],
  ['chandigarh', 'restaurant', 'cd-pal', 'Pal Dhaba', 'Casual', '🍖', 'nonveg', 'A Sector 28 legend since 1972 for tandoori platters.', 0.9],
  ['chandigarh', 'street', 'cd-sindhi', 'Sindhi Sweets (Sector 17)', 'Casual', '🍯', 'sweets', 'Crisp jalebi, samosa and rabri.', 0.8],
  ['chandigarh', 'cafe', 'cd-backpackers', 'Backpackers Café (Elante)', 'Vibrant', '🎒', 'cafe', 'A café at Elante Mall.', 1],
  ['chandigarh', 'restaurant', 'cd-barrels', 'Barrels & Grills (Elante)', 'Vibrant', '🍺', 'pub', 'Grills and drinks at Elante Mall.', 1.2],
  ['chandigarh', 'restaurant', 'cd-brooklyn', 'Brooklyn Central (Elante)', 'Vibrant', '🗽', 'pub', 'A mall bar and kitchen.', 1.2],
  ['chandigarh', 'cafe', 'cd-chaayos', 'Chaayos (Elante)', 'Casual', '🫖', 'cafe', 'Chai and snacks.', 0.9],
  ['chandigarh', 'restaurant', 'cd-nandos', 'Nando’s (Elante)', 'Vibrant', '🍗', 'nonveg', 'Peri-peri chicken.', 1.3],
  ['chandigarh', 'restaurant', 'cd-beercafe', 'The Beer Café (Elante)', 'Vibrant', '🍻', 'pub', 'A mall beer café.', 1.1],
  ['chandigarh', 'restaurant', 'cd-swagath', 'Swagath (Elante)', 'Casual', '🍤', 'nonveg', 'Coastal and South Indian seafood.', 1.2],
  ['chandigarh', 'restaurant', 'cd-elantesocial', 'Elante Social', 'Vibrant', '🎧', 'pub', 'The Social café-bar at Elante Mall.', 1.2],
  ['chandigarh', 'restaurant', 'cd-kulcha', 'Amritsari Kulcha Hub', 'Casual', '🫓', 'veg', 'Authentic Amritsari kulchas in Sector 9.', 0.8],

  /* ------------------------------- Nagpur ------------------------------- */
  ['nagpur', 'restaurant', 'ng-prachand', 'Prachand Saoji', 'Casual', '🌶️', 'nonveg', 'Saoji cuisine at Telephone Exchange Square.', 0.9],
  ['nagpur', 'cafe', 'ng-aragma', 'Café Aragma', 'Cozy', '☕', 'cafe', 'A Sitabuldi café.', 1],
  ['nagpur', 'cafe', 'ng-allthats', 'All That’s Coffee', 'Cozy', '☕', 'cafe', 'A Dharampeth coffee shop.', 1],
  ['nagpur', 'cafe', 'ng-pablo', 'Pablo', 'Vibrant', '🍰', 'cafe', 'A Civil Lines café with desserts, Italian and Asian dishes.', 1.1],
  ['nagpur', 'cafe', 'ng-eataly', 'Eataly Cafe', 'Cozy', '🍕', 'cafe', 'A Civil Lines café.', 1.1],

  /* -------------------------------- Kochi -------------------------------- */
  ['kochi', 'restaurant', 'kc-ginger', 'Ginger House', 'Romantic', '🫚', 'fine', 'A waterfront restaurant hidden behind a warehouse.', 1.5],
  ['kochi', 'restaurant', 'kc-grandpavilion', 'Grand Pavilion (Grand Hotel)', 'Romantic', '🏨', 'fine', 'Elegant, retro-styled hotel dining on MG Road.', 1.6],
  ['kochi', 'restaurant', 'kc-oceanos', 'Oceanos', 'Casual', '🦞', 'nonveg', 'A locally popular seafood restaurant.', 1.3],
  ['kochi', 'restaurant', 'kc-paragon', 'Paragon (Lulu Mall)', 'Casual', '🐟', 'nonveg', 'Kerala seafood and meals.', 1.2],
  ['kochi', 'cafe', 'kc-cocoa', 'Cocoa Tree (MG Road)', 'Cozy', '🍫', 'cafe', 'A well-liked MG Road café.', 1],
  ['kochi', 'cafe', 'kc-bubble', 'Bubble Café (Vivanta)', 'Cozy', '🫧', 'cafe', 'Hotel café on Marine Drive.', 1.4],

  /* ------------------- Jain food in the Madhya Pradesh cities ------------------- */
  ['indore', 'restaurant', 'in-jainbhoj', 'Jain Bhojnalya', 'Casual', '🪷', 'jain', 'Pure Jain food without onion or garlic, prepared on demand.', 0.8],
  ['jabalpur', 'restaurant', 'jb-digamber', 'Digamber Restaurant', 'Casual', '🪷', 'jain', 'Tasty Jain meals; onion- and garlic-free dishes.', 1],
  ['jabalpur', 'restaurant', 'jb-jaindelight', 'Food of Indians by Jain Delight', 'Casual', '🪷', 'jain', 'A Napier Town restaurant serving Jain food.', 1],

  /* ---------------------------- Jain food in Delhi ---------------------------- */
  ['delhi', 'restaurant', 'dl-rajasthali', 'Rajasthali (Select Citywalk)', 'Cozy', '🏜️', 'jain', 'Rajasthani dishes with Jain options at Select Citywalk.', 1.4],
  ['delhi', 'restaurant', 'dl-saatvik', 'Saatvik Restaurant (Green Park)', 'Cozy', '🪷', 'jain', 'Satvik, Jain-friendly vegetarian dining.', 1],
  ['delhi', 'restaurant', 'dl-veggulati', 'Veg Gulati (Karol Bagh)', 'Casual', '🍽️', 'jain', 'Gujarati and Rajasthani thalis, Jain-friendly.', 1],
  ['delhi', 'restaurant', 'dl-eleven', 'Eleven Course (Kamla Nagar)', 'Casual', '🥞', 'jain', 'Vegetarian North and South Indian with Jain options.', 0.95],
  ['delhi', 'restaurant', 'dl-baa', 'Baa Bistro', 'Cozy', '🪷', 'jain', 'Pure veg with pure Jain and satvik dishes.', 1.4],
  ['delhi', 'restaurant', 'dl-bhagat', 'Bhagat Tarachand', 'Casual', '🥘', 'jain', 'A long-standing favourite for Jain foodies.', 1],

  /* ---- More places for the smaller cities (names from web searches; scale roughly follows the typical cost for two) ---- */
  ['kolkata', 'restaurant', 'kl-6bp', '6 Ballygunge Place', 'Romantic', '🐟', 'fine', 'Authentic Bengali cuisine in an elegant, intimate Ballygunge setting.', 1.5],
  ['kolkata', 'cafe', 'kl-sienna', 'Sienna Store & Café', 'Cozy', '🎨', 'cafe', 'Quirky decor, mosaic art and good coffee.', 1.1],
  ['kolkata', 'restaurant', 'kl-olterra', 'Olterra', 'Romantic', '🌇', 'fine', 'A Park Street area rooftop setting made for date nights.', 1.5],
  ['kolkata', 'cafe', 'kl-pssocial', 'Park Street SOCIAL', 'Vibrant', '🎧', 'pub', 'Contemporary café with a creative all-day menu.', 1.2],
  ['kolkata', 'cafe', 'kl-franziska', 'Patisserie by Franziska', 'Romantic', '🍰', 'cafe', 'Decadent desserts and fine pastry work on Park Street.', 1.3],
  ['kolkata', 'restaurant', 'kl-oudh', 'Oudh 1590', 'Romantic', '👑', 'nonveg', 'Royal Awadhi dining with Mughal-inspired decor.', 1.7],
  ['kolkata', 'restaurant', 'kl-spicekraft', 'Spice Kraft', 'Cozy', '🌶️', 'fine', 'Asian, Lebanese and Continental dishes in eye-catching decor.', 1.4],
  ['kolkata', 'restaurant', 'kl-zucca', 'Zucca Lounge', 'Vibrant', '🛋️', 'pub', 'Pretty cabanas you can book for a private evening.', 1.5],

  ['pune', 'restaurant', 'pn-boteco', 'Boteco (Koregaon Park)', 'Romantic', '🥩', 'pub', 'Cosy Brazilian spot for churrasco, pão de queijo and beer.', 1.5],
  ['pune', 'restaurant', 'pn-darios', 'Dario’s (Koregaon Park)', 'Romantic', '🍝', 'pub', 'Italian, Mexican and vegan dishes with indoor and outdoor seating.', 1.4],
  ['pune', 'cafe', 'pn-pagdandi', 'Pagdandi Books Chai Cafe', 'Cozy', '📚', 'cafe', 'Sip chai surrounded by shelves of books.', 0.85],
  ['pune', 'cafe', 'pn-chafa', 'Chafa Café and Studio', 'Cozy', '🌸', 'cafe', 'A calm Koregaon Park café with wholesome, varied dishes.', 1],
  ['pune', 'cafe', 'pn-108', 'One O Eight Cafe', 'Casual', '🥣', 'cafe', 'Smoothie and acai bowls for a lighter date.', 1],
  ['pune', 'cafe', 'pn-vohuman', 'Vohuman Café', 'Casual', '🫖', 'cafe', 'An old Irani café for bun maska, chai and omelettes.', 0.75],

  ['jaipur', 'cafe', 'jp-poppin', 'Café Poppin (C-Scheme)', 'Romantic', '⛲', 'cafe', 'Patio furniture, a fountain and a garden-like feel.', 1.1],
  ['jaipur', 'cafe', 'jp-bae', 'Café Bae', 'Vibrant', '☕', 'cafe', 'Modern interiors and cosy seating in C-Scheme.', 1],
  ['jaipur', 'cafe', 'jp-stepout', 'Stepout Cafe & Book Lounge', 'Cozy', '📖', 'cafe', 'A book lounge with Lebanese, Mexican and Italian options.', 1],
  ['jaipur', 'cafe', 'jp-taruveda', 'Taruveda', 'Romantic', '🌿', 'cafe', 'A home-like, earthy café set amid lush greens.', 1.1],
  ['jaipur', 'restaurant', 'jp-miroh', 'Miroh (C-Scheme)', 'Vibrant', '🍗', 'nonveg', 'Non-veg favourites with good vibes.', 1.3],
  ['jaipur', 'cafe', 'jp-jaies', 'Jaies Cafe (MI Road)', 'Casual', '🥤', 'cafe', 'A relaxed MI Road café, around ₹650 for two.', 0.8],
  ['jaipur', 'cafe', 'jp-ich', 'Indian Coffee House (MI Road)', 'Cozy', '☕', 'south', 'A heritage cooperative café with filter coffee and classics.', 0.7],

  ['kochi', 'cafe', 'kc-loafers', 'Loafers Corner Cafe', 'Vibrant', '🥪', 'cafe', 'A lively Fort Kochi café in a 200-year-old building.', 1],
  ['kochi', 'cafe', 'kc-qissa', 'Qissa Café', 'Cozy', '🍫', 'cafe', 'Chocolate cakes and omelettes near Fort Kochi, about ₹600 for two.', 0.75],
  ['kochi', 'cafe', 'kc-pepper', 'Pepper House Cafe', 'Romantic', '🌳', 'cafe', 'Wooden benches and a lush garden by the harbour.', 1.4],
  ['kochi', 'cafe', 'kc-deli', 'Deli Cafe (Kaloor)', 'Cozy', '🥐', 'cafe', 'A couple-friendly café in Kaloor.', 0.95],
  ['kochi', 'cafe', 'kc-cafe17', 'Cafe 17', 'Cozy', '☕', 'cafe', 'A trendy, modern café in the heart of Kochi.', 0.9],
  ['kochi', 'cafe', 'kc-tonicos', 'Tonico’s Cafe', 'Romantic', '🥩', 'cafe', 'Good coffee, steaks and soothing music.', 1.1],

  ['nagpur', 'cafe', 'ng-illusions', 'Café Illusions (Dharampeth)', 'Cozy', '☕', 'cafe', 'A Dharampeth café on Ambazari Road.', 1],
  ['nagpur', 'cafe', 'ng-mocha', 'Mocha (Dharampeth)', 'Romantic', '💡', 'pub', 'Beautiful lighting; known for peri peri pizza and grilled fish.', 1.1],
  ['nagpur', 'cafe', 'ng-villa167', 'Villa 167 Cafe', 'Romantic', '🌇', 'cafe', 'Cosy seating and scenic rooftop views.', 1.1],
  ['nagpur', 'restaurant', 'ng-uptown', 'Uptown501 Cafe-lounge', 'Vibrant', '🍸', 'pub', 'A Dharampeth multicuisine café-lounge.', 1.5],
  ['nagpur', 'restaurant', 'ng-naivedhyam', 'Naivedhyam Restaurant', 'Casual', '🍛', 'north', 'Chinese and North Indian in Sitabuldi.', 1.2],

  ['ahmedabad', 'cafe', 'ah-zen', 'Zen Cafe (Satellite)', 'Cozy', '🪷', 'pub', 'Tranquil, modern café with Asian, Mediterranean and American dishes.', 1.3],
  ['ahmedabad', 'restaurant', 'ah-momo', 'MoMo Cafe (Courtyard by Marriott)', 'Romantic', '🍽️', 'fine', 'Hotel dining with Asian, Indian and Continental cuisines.', 1.9],
  ['ahmedabad', 'cafe', 'ah-project', 'Project Cafe', 'Romantic', '💞', 'cafe', 'Cosy corners and aesthetic walls popular with couples.', 1.1],
  ['ahmedabad', 'restaurant', 'ah-mexicano', 'Mexicano By The Bay', 'Vibrant', '🌮', 'pub', 'Authentic Mexican food, around ₹800 for two.', 1],
  ['ahmedabad', 'cafe', 'ah-bluetokai', 'Blue Tokai Coffee Roasters (CG Square)', 'Cozy', '☕', 'cafe', 'Single-estate arabica and pour-overs.', 1.1],
  ['ahmedabad', 'cafe', 'ah-danny', 'Danny’s Coffee Bar', 'Cozy', '☕', 'cafe', 'A C G Road coffee bar.', 0.9],
  ['ahmedabad', 'cafe', 'ah-coffeestand', 'Coffee Stand', 'Casual', '🥤', 'cafe', 'A casual C G Road coffee stop.', 0.8],

  /* ---- Round 3: more real places in every city (names from web searches; scale follows typical cost for two where known) ---- */
  ['bhopal', 'restaurant', 'bp-raw', 'Raw the Restrobar', 'Romantic', '🍽️', 'fine', 'Modern dining by Chef AJ, known for its contemporary menu.', 1.6],
  ['bhopal', 'restaurant', 'bp-winds', 'Winds n Waves', 'Romantic', '🌊', 'north', 'Waterfront Indian and Asian dining near Boat Club on Van Vihar Road.', 1.4],
  ['bhopal', 'restaurant', 'bp-flyingsaucer', 'Flying Saucer (Arera Colony)', 'Vibrant', '🛸', 'pub', 'A popular Arera Colony hangout.', 1.2],
  ['bhopal', 'restaurant', 'bp-littleitaly', 'Little Italy (Arera Colony)', 'Romantic', '🍕', 'pub', 'Italian restaurant in Arera Colony, busiest around dinner time.', 1.3],
  ['bhopal', 'cafe', 'bp-amado', 'Cafe Amado', 'Romantic', '☕', 'cafe', 'Aesthetic Continental café in Arera Colony, about ₹600 for two.', 0.75],
  ['bhopal', 'cafe', 'bp-alibaba', 'Ali Baba Caves', 'Vibrant', '🏺', 'cafe', 'Rooftop café in Gulmohar Colony, about ₹800 for two.', 0.9],
  ['bhopal', 'restaurant', 'bp-sky55', 'Sky 55', 'Romantic', '🌃', 'pub', 'Rooftop dining at Maharana Pratap Nagar, about ₹1,200 for two.', 1.2],
  ['bhopal', 'restaurant', 'bp-shikha', 'Hotel Shikha Palace', 'Casual', '🍛', 'north', 'Rooftop restaurant near Peer Gate, about ₹600 for two.', 0.75],
  ['bhopal', 'cafe', 'bp-kudos', 'Cafe Kudos', 'Casual', '☕', 'cafe', 'A top-floor café in Arera Colony, about ₹600 for two.', 0.75],
  ['bhopal', 'restaurant', 'bp-spicehouse', 'The Spice House (New Market)', 'Casual', '🌶️', 'north', 'A New Market spot, about ₹450 for two.', 0.6],
  ['indore', 'restaurant', 'in-indiyaoye', 'Indiya Oye (Radisson Blu)', 'Romantic', '🍖', 'fine', 'Fine dining in North Indian and Mughlai, kebabs and desserts.', 2.6],
  ['indore', 'restaurant', 'in-kebabsville', 'Kebabsville (Sayaji Hotel)', 'Casual', '🍢', 'nonveg', 'Famous for kebabs and meat curries in Vijay Nagar.', 1.8],
  ['indore', 'restaurant', 'in-vidorra', 'Vidorra (Old Palasia)', 'Vibrant', '🌃', 'pub', 'A rooftop that comes alive at night, with neon lights and live music.', 1.6],
  ['indore', 'cafe', 'in-farzi', 'Farzi Café (Vijay Nagar)', 'Vibrant', '🎭', 'pub', 'Indo-western menu, a terrace with city views and a lively night vibe.', 1.5],
  ['indore', 'cafe', 'in-mamaloca', 'Mama Loca', 'Vibrant', '🌮', 'pub', 'Colourful Mediterranean, Lebanese and Greek menu with weekly live music.', 1.3],
  ['indore', 'cafe', 'in-terazza', 'Cafe Terazza', 'Romantic', '🌌', 'pub', 'A rooftop café for Continental and Asian food under the night sky.', 1.1],
  ['indore', 'cafe', 'in-highgarden', 'HighGarden Cafe', 'Romantic', '🪴', 'cafe', 'A rooftop café with outdoor seating and weekend live music.', 1.0],
  ['indore', 'cafe', 'in-eyry', 'The Eyry', 'Cozy', '☕', 'cafe', 'Cosy, chic café known for coffee and multiple brewing options.', 1.0],
  ['jabalpur', 'cafe', 'jb-houseofblend', 'House of Blend', 'Cozy', '☕', 'cafe', 'Quality coffee and a tranquil atmosphere for long conversations.', 1.0],
  ['jabalpur', 'restaurant', 'jb-jharokha', 'Jharokha Restaurant', 'Casual', '🥘', 'veg', 'Vegetarian dishes with steady quality, in Napier Town.', 1.0],
  ['jabalpur', 'restaurant', 'jb-70mm', '70 mm Dining', 'Casual', '🎬', 'north', 'An Indian restaurant in Napier Town.', 1.0],
  ['delhi', 'restaurant', 'dl-ottimo', 'Ottimo at Westview (ITC Maurya)', 'Romantic', '🌇', 'fine', 'A rooftop with panoramic green-belt views and modern Western cuisine.', 3.4],
  ['delhi', 'restaurant', 'dl-qba', 'Q’ba (Connaught Place)', 'Romantic', '🕯️', 'fine', 'Fine dining in the inner circle of Connaught Place.', 1.9],
  ['delhi', 'restaurant', 'dl-thaihigh', 'Thai High (Mehrauli)', 'Romantic', '🏯', 'fine', 'Thai food with a rooftop view of the Qutub Minar.', 1.8],
  ['delhi', 'restaurant', 'dl-amalfi', 'Amalfi (Greater Kailash)', 'Romantic', '🍝', 'pub', 'Italian with rooftop and outdoor dining.', 1.5],
  ['delhi', 'cafe', 'dl-summerhouse', 'Summer House Cafe (Hauz Khas Village)', 'Vibrant', '🍹', 'pub', 'A very large terrace, cocktails and live music gigs.', 1.4],
  ['delhi', 'cafe', 'dl-elmas', 'Elma’s Bakery', 'Cozy', '🥧', 'cafe', 'Vintage charm and baked treats in Hauz Khas Village.', 1.0],
  ['delhi', 'cafe', 'dl-bluedoor', 'The Blue Door Cafe (Khan Market)', 'Cozy', '🚪', 'cafe', 'Salads and sandwiches in a cosy little café.', 1.0],
  ['delhi', 'restaurant', 'dl-sodabottle', 'SodaBottleOpenerWala (Khan Market)', 'Vibrant', '🥤', 'cafe', 'A Bombay Irani café-restaurant with an outdoor balcony and Parsi specialities.', 1.2],
  ['delhi', 'restaurant', 'dl-garden', 'The Garden Restaurant (Lodhi Gardens)', 'Romantic', '🌳', 'fine', 'A restaurant set in a garden, loved for its breath-taking ambience.', 1.9],
  ['mumbai', 'restaurant', 'mb-olive', 'Olive Bar & Kitchen (Pali Hill)', 'Romantic', '🫒', 'fine', 'A romantic courtyard setting with Mediterranean food.', 2.4],
  ['mumbai', 'restaurant', 'mb-asilo', 'Asilo (The St. Regis)', 'Romantic', '🍸', 'fine', 'A rooftop lounge with panoramic city views, grills and cocktails.', 3.2],
  ['mumbai', 'restaurant', 'mb-allamanda', 'Allamanda Terrace (Hotel Marine Plaza)', 'Romantic', '🌊', 'fine', 'A rooftop with views of the Arabian Sea and the Queen’s Necklace.', 2.2],
  ['mumbai', 'restaurant', 'mb-dome', 'The Dome (InterContinental)', 'Romantic', '🌆', 'pub', 'A rooftop with panoramic views of the city skyline.', 2.4],
  ['mumbai', 'cafe', 'mb-le15', 'Le15 Patisserie', 'Romantic', '🍬', 'cafe', 'Pastel macarons, including the signature paan macaron.', 1.4],
  ['mumbai', 'cafe', 'mb-sealounge', 'Sea Lounge (Taj Mahal Palace)', 'Romantic', '🫖', 'cafe', 'Famous for a high tea with scones, tarts and finger sandwiches.', 2.6],
  ['mumbai', 'cafe', 'mb-bagel', 'The Bagel Shop (Bandra)', 'Cozy', '🥯', 'cafe', 'A quaint café with fairy-lit outdoor seating and fresh bagels.', 1.1],
  ['mumbai', 'restaurant', 'mb-ideal', 'Ideal Corner', 'Casual', '🍲', 'nonveg', 'A Fort-area Parsi eatery serving dhansak, farcha and akuri sandwiches.', 1.0],
  ['mumbai', 'restaurant', 'mb-military', 'Café Military', 'Casual', '☕', 'nonveg', 'One of the few remaining Irani cafés, with no-frills Parsi food.', 0.9],
  ['mumbai', 'cafe', 'mb-yazdani', 'Yazdani Bakery', 'Casual', '🍞', 'cafe', 'A Parsi bakery café tucked into a Fort by-lane.', 0.7],
  ['mumbai', 'restaurant', 'mb-gajalee', 'Gajalee (Vile Parle)', 'Casual', '🦐', 'nonveg', 'Malvani coastal seafood with prawns, surmai and crab.', 1.6],
  ['mumbai', 'restaurant', 'mb-mahesh', 'Mahesh Lunch Home (Fort)', 'Casual', '🐟', 'nonveg', 'Mangalorean seafood: tandoori pomfret and fish gassi.', 1.6],
  ['mumbai', 'restaurant', 'mb-jaihind', 'Jai Hind Lunch Home', 'Casual', '🐠', 'nonveg', 'A seafood favourite with branches in Bandra, Lower Parel and Dadar.', 1.2],
  ['bengaluru', 'restaurant', 'bl-skyye', 'Skyye (UB City)', 'Romantic', '🍸', 'pub', 'A rooftop bar atop UB City with skyline views.', 2.2],
  ['bengaluru', 'restaurant', 'bl-highultra', 'High Ultra Lounge', 'Romantic', '🌃', 'fine', 'Fine dining on the 31st floor of World Trade Centre.', 2.6],
  ['bengaluru', 'restaurant', 'bl-13thfloor', 'The 13th Floor', 'Vibrant', '🌇', 'pub', 'A rooftop with spectacular skyline views.', 1.8],
  ['bengaluru', 'restaurant', 'bl-chavadi', 'Chavadi', 'Romantic', '🔥', 'fine', 'Rooftop deck dining with a wood-fire oven near Bannerghatta Road.', 1.7],
  ['bengaluru', 'restaurant', 'bl-phobidden', 'Phobidden Fruit (Indiranagar)', 'Romantic', '🍜', 'fine', 'Vietnamese food with outdoor seating amid greenery.', 1.8],
  ['bengaluru', 'restaurant', 'bl-bytheblue', 'By the Blue (Grand Mercure)', 'Romantic', '🏊', 'fine', 'Poolside dinners at Grand Mercure, Koramangala.', 2.2],
  ['bengaluru', 'restaurant', 'bl-rimnaam', 'Rim Naam (The Oberoi)', 'Romantic', '🌴', 'fine', 'Outdoor dining amid lush greenery at The Oberoi.', 3.0],
  ['bengaluru', 'restaurant', 'bl-olive', 'Olive Bar & Kitchen (Bengaluru)', 'Romantic', '🫒', 'fine', 'Rustic decor and a courtyard, with a Mediterranean-inspired menu.', 2.0],
  ['bengaluru', 'cafe', 'bl-dyu', 'Dyu Art Cafe', 'Cozy', '🎨', 'cafe', 'A serene Koramangala café with comfy seating.', 0.95],
  ['bengaluru', 'cafe', 'bl-karmakappi', 'Karma Kappi', 'Casual', '☕', 'cafe', 'A quaint Jayanagar café with international brews and mango Vietnamese coffee.', 0.5],
  ['bengaluru', 'cafe', 'bl-murumuru', 'Muru Muru', 'Cozy', '🏠', 'cafe', 'Desi bites and coffee in an old-school house setting in Indiranagar.', 0.9],
  ['bengaluru', 'cafe', 'bl-caffeine', 'The Caffeine Chronicles', 'Cozy', '☕', 'cafe', 'A haven for coffee lovers with a wide range of brews.', 1.0],
  ['bengaluru', 'restaurant', 'bl-biere', 'Biere Club', 'Vibrant', '🍻', 'pub', 'Bengaluru’s first craft brewery, serving small-batch beer.', 1.7],
  ['bengaluru', 'restaurant', 'bl-arbor', 'Arbor Brewing Company', 'Vibrant', '🍺', 'pub', 'A craft brewery with a menu for beer lovers and teetotallers alike.', 1.7],
  ['bengaluru', 'restaurant', 'bl-reservoir', 'The Reservoir', 'Vibrant', '🎶', 'pub', 'Industrial-chic setting with craft cocktails and live music.', 1.8],
  ['bengaluru', 'restaurant', 'bl-loft38', 'Loft 38', 'Vibrant', '💃', 'pub', 'A Whitefield spot popular for dancing and date nights.', 1.6],
  ['bengaluru', 'restaurant', 'bl-fennys', 'Fenny’s Lounge & Kitchen', 'Cozy', '🍸', 'pub', 'A lounge and kitchen in the heart of the city.', 1.4],
  ['hyderabad', 'restaurant', 'hy-overthemoon', 'Over The Moon (Jubilee Hills)', 'Romantic', '🌙', 'fine', 'Floor-to-ceiling glass walls with a view of the Durgam Cheruvu bridge.', 2.4],
  ['hyderabad', 'restaurant', 'hy-mudbrick', 'MudBrick Kitchen & Bar', 'Vibrant', '🎸', 'pub', 'Live music, large outdoor seating and fusion cuisine.', 1.8],
  ['hyderabad', 'restaurant', 'hy-olivebistro', 'Olive Bistro', 'Romantic', '🕯️', 'fine', 'White, peaceful decor with views of a secret lake.', 2.0],
  ['hyderabad', 'restaurant', 'hy-f9', 'F9 Test Kitchen', 'Cozy', '🪨', 'pub', 'A classy yet casual setting surrounded by rocks and boulders.', 1.5],
  ['hyderabad', 'cafe', 'hy-aura', 'Aura Café', 'Cozy', '💡', 'cafe', 'Wooden panels, brick walls and Edison lamps.', 1.3],
  ['hyderabad', 'restaurant', 'hy-jewel', 'Jewel of Nizam (Golkonda Resort)', 'Romantic', '🏰', 'fine', 'A rooftop facing the floodlit Golkonda Fort, with weekend ghazals.', 3.0],
  ['hyderabad', 'restaurant', 'hy-hardrock', 'Hard Rock Café (Banjara Hills)', 'Vibrant', '🎸', 'pub', 'Live performances and American, Continental and Tex-Mex food.', 1.7],
  ['hyderabad', 'cafe', 'hy-autumn', 'Autumn Leaf Café', 'Cozy', '🍂', 'cafe', 'A café in a Chettinad home, set amid greenery.', 1.1],
  ['hyderabad', 'cafe', 'hy-cravery', 'Cravery Cafe', 'Casual', '☕', 'cafe', 'A casual Jubilee Hills café with a diverse menu.', 0.9],
  ['hyderabad', 'cafe', 'hy-thirdwave', 'Third Wave Coffee (Gachibowli)', 'Cozy', '☕', 'cafe', 'Specialty coffee and cold brew.', 1.0],
  ['hyderabad', 'cafe', 'hy-bluetokai', 'Blue Tokai Coffee Roasters (Gachibowli)', 'Cozy', '☕', 'cafe', 'Specialty coffee and single-origin pour-overs.', 1.1],
  ['hyderabad', 'restaurant', 'hy-shadab', 'Hotel Shadab', 'Casual', '🍲', 'nonveg', 'Known for haleem, nihari, Nizami handi and biryani.', 1.0],
  ['hyderabad', 'cafe', 'hy-nimrah', 'Nimrah Cafe', 'Casual', '🫖', 'cafe', 'A classic Irani café almost under the arches of the Charminar.', 0.5],
  ['chennai', 'restaurant', 'ch-chipstead', 'Chipstead (Taj Coromandel)', 'Romantic', '🍷', 'fine', 'A well-known Nungambakkam restaurant with wine and beer.', 2.4],
  ['chennai', 'restaurant', 'ch-bombaybrasserie', 'Bombay Brasserie', 'Romantic', '✨', 'north', 'Vibrant walls, fancy lights and comfortable seating.', 1.5],
  ['chennai', 'restaurant', 'ch-blindch3mistry', 'Blind Ch3mistry', 'Vibrant', '🛋️', 'pub', 'Hammocks, swings, cushioned benches and signature milkshakes.', 1.2],
  ['chennai', 'restaurant', 'ch-ignna', 'IGNNA by Midnight Sun', 'Romantic', '🌙', 'fine', 'Middle Eastern food with rustic charm and an open-air terrace.', 1.6],
  ['chennai', 'restaurant', 'ch-kayal', 'Kayal (Le Méridien)', 'Romantic', '🦐', 'fine', 'Seafood at Le Méridien, with salmon and prawns.', 2.3],
  ['chennai', 'restaurant', 'ch-crimson', 'Crimson Chakra', 'Romantic', '🕯️', 'north', 'A space for candlelight dinners, with North and South Indian food.', 1.5],
  ['chennai', 'cafe', 'ch-atte', 'Atte – Glocal Cafe', 'Cozy', '☕', 'cafe', 'A Besant Nagar café, not far from the beach.', 1.0],
  ['chennai', 'cafe', 'ch-englishtearoom', 'The English Tearoom', 'Romantic', '🫖', 'cafe', 'One of Chennai’s most romantic cafés, in Alwarpet.', 1.0],
  ['chennai', 'cafe', 'ch-gelatoaffair', 'Gelato Affair', 'Casual', '🍨', 'cafe', 'Handcrafted gelato, from saffron pistachio to dark chocolate chilli.', 0.9],
  ['chennai', 'cafe', 'ch-amelies', 'Amelie’s', 'Vibrant', '🌇', 'cafe', 'A vibrant rooftop café in Alwarpet.', 1.1],
  ['chennai', 'cafe', 'ch-sandys', 'Sandy’s Chocolate Laboratory', 'Cozy', '🍫', 'cafe', 'A chocolate-focused café in Nungambakkam.', 1.0],
  ['chennai', 'cafe', 'ch-courtyardcafe', 'The Secret Courtyard Café', 'Romantic', '🏮', 'cafe', 'Rustic decor, fairy lights, coffee and fresh pastries.', 1.0],
  ['chennai', 'cafe', 'ch-scooby', 'Scooby Cafe', 'Cozy', '🐕', 'cafe', 'A woodsy, warm café where pets are welcome.', 0.9],
  ['chennai', 'cafe', 'ch-wildgarden', 'The Wild Garden Cafe', 'Romantic', '🌺', 'cafe', 'Popular with couples; its chocolate lava cake is a hit.', 1.1],
  ['chennai', 'restaurant', 'ch-ratna', 'Ratna Cafe', 'Casual', '🥣', 'south', 'Known since 1948 for its sambar idli.', 0.6],
  ['chennai', 'restaurant', 'ch-sangeetha', 'Sangeetha Veg Restaurant', 'Casual', '🍽️', 'south', 'South Indian thali and traditional favourites, with outlets in Mylapore and Adyar.', 0.8],
  ['lucknow', 'restaurant', 'lk-oudhyana', 'Oudhyana', 'Romantic', '🕌', 'fine', 'Awadhi fine dining: galouti kebab, zafrani pulao and shahi tukda.', 1.7],
  ['lucknow', 'restaurant', 'lk-spicefactory', 'The Spice Factory (Gomti Nagar)', 'Romantic', '🌶️', 'fine', 'Multi-cuisine fine dining in a peaceful setting.', 1.5],
  ['lucknow', 'restaurant', 'lk-vintagemachine', 'Vintage Machine (Gomti Nagar)', 'Romantic', '⚙️', 'pub', 'A retro-style Italian café and cocktail bar.', 1.5],
  ['lucknow', 'restaurant', 'lk-zaika', 'Zaika by Gemini Continental', 'Cozy', '🍽️', 'fine', 'An elegant, modern restaurant in Hazratganj.', 1.5],
  ['lucknow', 'cafe', 'lk-cherrytree', 'Cherry Tree Café (Hazratganj)', 'Cozy', '🍒', 'cafe', 'Fresh coffee, sandwiches, desserts and cakes in the heart of Hazratganj.', 1.0],
  ['lucknow', 'cafe', 'lk-macaron', 'Macaron Patisserie', 'Romantic', '🧁', 'cafe', 'A Victorian-style bakery in Hazratganj with excellent pastries and cakes.', 1.1],
  ['lucknow', 'restaurant', 'lk-homesweet', 'Home Sweet Home (Hazratganj)', 'Cozy', '🍝', 'pub', 'Excellent Italian fare in Hazratganj.', 1.4],
  ['lucknow', 'restaurant', 'lk-tanatan', 'Tanatan (Hazratganj)', 'Vibrant', '🥂', 'pub', 'A Hazratganj spot open from noon until midnight.', 1.2],
  ['lucknow', 'cafe', 'lk-sheroes', 'Sheroes Hangout', 'Cozy', '☕', 'cafe', 'A Gomti Nagar café opposite Dr Ambedkar Park.', 0.7],
  ['lucknow', 'restaurant', 'lk-zao', 'ZAO (Cyber Heights)', 'Romantic', '🍣', 'fine', 'A Gomti Nagar restaurant at Cyber Heights.', 1.8],
  ['lucknow', 'cafe', 'lk-roastery', 'Roastery House Cafe', 'Cozy', '☕', 'cafe', 'A Gomti Nagar coffee café.', 0.95],
  ['lucknow', 'cafe', 'lk-planters', 'Planters Tea Bar and Book Café', 'Romantic', '📚', 'cafe', 'A cosy tea bar and book café with live music.', 1.0],
  ['chandigarh', 'restaurant', 'cd-tao', 'Tao (Sector 26)', 'Romantic', '🏮', 'fine', 'Kashmiri and North Indian dining, around ₹2,000 for two.', 1.9],
  ['chandigarh', 'restaurant', 'cd-asiakitchen', 'Asia Kitchen by Mainland China (Elante)', 'Romantic', '🥢', 'fine', 'Chinese and Japanese at Elante Mall.', 1.8],
  ['chandigarh', 'restaurant', 'cd-kylin', 'Kylin Experience (Elante)', 'Romantic', '🍣', 'fine', 'Chinese and Japanese cuisine at Elante Mall.', 2.0],
  ['chandigarh', 'restaurant', 'cd-virgin', 'Virgin Courtyard', 'Romantic', '🍷', 'pub', 'Italian pasta, pizza and tiramisu, great for a romantic dinner.', 1.4],
  ['chandigarh', 'cafe', 'cd-nikbakers', 'Nik Baker’s (Sector 35)', 'Cozy', '🎂', 'cafe', 'A bakery café known for cakes, with a peaceful ambience.', 1.1],
  ['chandigarh', 'cafe', 'cd-ovenfresh', 'OvenFresh (Sector 35)', 'Casual', '🥞', 'cafe', 'Salads, pancakes, omelettes, pasta and shakes.', 0.9],
  ['chandigarh', 'cafe', 'cd-aja', 'AJA Chandigarh', 'Cozy', '🥗', 'cafe', 'A health-food café with vegan and gluten-free options.', 1.2],
  ['chandigarh', 'cafe', 'cd-nomad', 'Café Nomad (Sector 7)', 'Romantic', '🧆', 'cafe', 'Authentic Middle-Eastern dishes with a beautiful ambience.', 1.2],
  ['chandigarh', 'cafe', 'cd-hedgehog', 'The Hedgehog Café (Sector 7-C)', 'Cozy', '📖', 'cafe', 'Books, music, Italian entrees, burgers and sandwiches.', 1.0],
  ['chandigarh', 'cafe', 'cd-willow', 'The Willow Café (Sector 10)', 'Cozy', '🌳', 'cafe', 'A country-style café with open-air seating.', 1.1],
  ['pune', 'restaurant', 'pn-atmosphere6', 'Atmosphere 6 (Viman Nagar)', 'Romantic', '🌆', 'fine', 'A rooftop with contemporary design and city views, open until 1 am.', 2.0],
  ['pune', 'restaurant', 'pn-incognito', 'Incognito (Viman Nagar)', 'Vibrant', '🕶️', 'pub', 'A Viman Nagar date-night spot.', 1.5],
  ['pune', 'restaurant', 'pn-chingari', 'Chingari', 'Romantic', '🔥', 'nonveg', 'A rooftop terrace with poolside seating, known for Mughlai.', 3.0],
  ['pune', 'restaurant', 'pn-paasha', 'Paasha (JW Marriott)', 'Romantic', '🌇', 'fine', 'Northwest Frontier cuisine on a rooftop with a view.', 2.5],
  ['jaipur', 'restaurant', 'jp-adda', 'Jaipur Adda (Bani Park)', 'Vibrant', '🎶', 'pub', 'A rooftop with modern cuisine and live music, open late.', 1.2],
  ['jaipur', 'restaurant', 'jp-terracegrill', 'The Terrace Grill', 'Romantic', '🕯️', 'fine', 'One of the oldest restaurants in the city, for rooftop candlelit dinners.', 1.5],
  ['jaipur', 'restaurant', 'jp-aquagrill', 'Aqua Grill (Bani Park)', 'Casual', '🔥', 'bbq', 'Rooftop city views with North Indian food and barbecue.', 1.4],
  ['jaipur', 'restaurant', 'jp-giardino', 'Giardino (Taj Jai Mahal Palace)', 'Romantic', '🏛️', 'fine', 'Italian in a palace with Rajasthani heritage decor.', 4.5],
  ['jaipur', 'restaurant', 'jp-suryamahal', 'Surya Mahal (Samode Haveli)', 'Romantic', '🪔', 'fine', 'Courtyard dining in a restored haveli, with live folk music.', 2.8],
  ['jaipur', 'restaurant', 'jp-forresta', 'The Forresta (Bani Park)', 'Romantic', '🌿', 'fine', 'Lush greenery and an elegant ambience for a romantic dinner.', 1.9],
  ['kolkata', 'restaurant', 'kl-aaheli', 'Aaheli', 'Romantic', '🐟', 'fine', 'One of Kolkata’s best-known Bengali restaurants.', 1.5],
  ['kolkata', 'restaurant', 'kl-bhojohori', 'Bhojohori Manna', 'Casual', '🍛', 'fine', 'Popular Bengali food, with an outlet in Salt Lake.', 1.2],
  ['kolkata', 'restaurant', 'kl-gondhoraj', 'Gondhoraj (Salt Lake)', 'Cozy', '🍤', 'fine', 'Casual dining with seafood and dessert specialities.', 1.2],
  ['kolkata', 'restaurant', 'kl-shiraz', 'Shiraz (Park Circus)', 'Casual', '🍚', 'nonveg', 'Known for Calcutta-style Awadhi biryani.', 1.0],
  ['kolkata', 'restaurant', 'kl-goldenjoy', 'Golden Joy (Tangra)', 'Casual', '🥡', 'chinese', 'An iconic restaurant in Kolkata’s Chinese quarter.', 1.2],
  ['kolkata', 'restaurant', 'kl-beijing', 'Beijing (Tangra)', 'Casual', '🥢', 'chinese', 'An iconic restaurant in Kolkata’s Chinese quarter.', 1.2],
  ['kolkata', 'restaurant', 'kl-calnostalgia', 'Calcutta Nostalgia', 'Cozy', '🏺', 'fine', 'A popular Bengali restaurant.', 1.3],
  ['kolkata', 'restaurant', 'kl-baburculture', 'Babu Culture', 'Cozy', '🛖', 'fine', 'A popular Bengali restaurant.', 1.2],
  ['kolkata', 'restaurant', 'kl-kasturi', 'Kasturi', 'Casual', '🍛', 'fine', 'A popular Bengali restaurant.', 1.1],
  ['ahmedabad', 'restaurant', 'ah-atithi', 'Atithi (Bodakdev)', 'Casual', '🍽️', 'veg', 'A renowned Gujarati thali restaurant, about ₹700 for two.', 0.8],
  ['ahmedabad', 'restaurant', 'ah-birmies', 'Birmies (Bodakdev)', 'Casual', '🍝', 'north', 'Comfort food — North Indian, Chinese and Mexican — at affordable prices.', 0.9],
  ['ahmedabad', 'restaurant', 'ah-neemchowk', 'Neem Chowk – Under The Neem Tree', 'Cozy', '🌳', 'north', 'A Bodakdev restaurant under a neem tree.', 1.0],
  ['ahmedabad', 'restaurant', 'ah-aagrah', 'Aagrah (Chandkheda)', 'Casual', '🥘', 'veg', 'Gujarati thali honouring the state’s festive dining.', 0.9],
  ['kochi', 'restaurant', 'kc-riceboat', 'The Rice Boat (Taj Malabar)', 'Romantic', '⛵', 'fine', 'A Taj restaurant on a floating boat, loved for seafood.', 2.8],
  ['kochi', 'restaurant', 'kc-arcanova', 'Arca Nova', 'Romantic', '🌊', 'fine', 'Kerala Latin-Christian cuisine overlooking the Arabian Sea.', 1.8],
  ['kochi', 'restaurant', 'kc-fusionbay', 'Fusion Bay', 'Casual', '🐟', 'nonveg', 'Seafood, including pollichathu, karimeen mappas and fish pappas.', 1.2],
  ['kochi', 'restaurant', 'kc-marina', 'Marina The Sea Face Restaurant', 'Romantic', '🌅', 'fine', 'Kerala seafood at a waterfront with ocean views.', 1.6],
  ['kochi', 'restaurant', 'kc-malabarjunction', 'Malabar Junction (Malabar House)', 'Romantic', '🏛️', 'fine', 'Well-regarded seafood in an intimate setting.', 2.4],
  ['nagpur', 'restaurant', 'ng-bellavista', 'Bellavista Cafe & Skybar', 'Romantic', '🌃', 'pub', 'Chinese and North Indian with a skybar in Civil Lines.', 1.1],
  ['nagpur', 'restaurant', 'ng-tao', 'TAO – Asian Kitchen', 'Romantic', '🥢', 'chinese', 'Chinese and Japanese cuisine in Civil Lines.', 1.8],
  ['nagpur', 'restaurant', 'ng-veggietude', 'Veggietude', 'Casual', '🥗', 'veg', 'Vegetarian Chinese and North Indian in Civil Lines.', 1.0],
  ['nagpur', 'restaurant', 'ng-amaira', 'Amaira', 'Cozy', '🍛', 'north', 'Continental and North Indian in Civil Lines.', 1.2],
  ['nagpur', 'restaurant', 'ng-littleitaly', 'Little Italy (Civil Lines)', 'Romantic', '🍕', 'pub', 'Italian and Mexican in Civil Lines.', 1.4],
  ['nagpur', 'cafe', 'ng-filtr16', 'Filtr 16 Brew Bar', 'Cozy', '☕', 'cafe', 'Beverages and Continental bites in Civil Lines.', 0.8],
  ['nagpur', 'restaurant', 'ng-meetingpoint', 'Meeting Point (Hotel Centre Point)', 'Casual', '🍽️', 'north', 'Continental and North Indian in Ramdaspeth.', 1.3],
  ['nagpur', 'restaurant', 'ng-bougainvillea', 'Bougainvillea', 'Cozy', '🌸', 'chinese', 'Chinese and North Indian in Ramdaspeth.', 1.2],
  ['nagpur', 'restaurant', 'ng-latestrecipe', 'The Latest Recipe (Le Meridien)', 'Romantic', '🥂', 'fine', 'Continental and North Indian at Le Meridien, Wardha Road.', 1.4],
]

export const ALL_CITY_VENUES = ROWS.map(([city, kind, id, name, vibe, emoji, type, tagline, scale]) => quick(city, kind, id, name, vibe, emoji, type, tagline, scale))

// Existing venues that serve Jain food (from the same searches).
export const JAIN_FRIENDLY_IDS = ['dl-saravana']
