/* More Bhopal venues. Names are real places; descriptions, menus and prices are ILLUSTRATIVE —
   hours, menus and prices change, so always confirm with the venue. */
import { makeVenue } from '../venueHelpers'

const B = (...args) => makeVenue('bhopal', ...args)

export const BHOPAL_MORE = [
  B('za', 'Za-aiqa (Noor-Us-Sabah Palace)', 'Romantic', '🌙', 'Awadhi · Mughlai · Peshwari',
    'Begum-era recipes in a heritage hotel overlooking the lake.',
    ['Heritage hotel', 'Lake views', 'Mughlai and Awadhi classics'],
    'Smart formal', 'A calm evening walk with views over the lake.',
    [
      [['Subz Seekh', 480, true], ['Dahi Ke Kebab', 520, true], ['Murgh Malai Tikka', 580, false], ['Galouti Kebab', 620, false]],
      [['Dal Za-aiqa', 560, true, 'House dal, slow-cooked'], ['Paneer Pasanda', 680, true], ['Bhopali Biryani', 780, false], ['Murgh Korma', 820, false], ['Mutton Rogan Josh', 920, false]],
      [['Masala Chai', 160, true], ['Fresh Lime Soda', 180, true], ['Rose Sharbat', 220, true], ['Kesar Lassi', 260, true]],
      [['Phirni', 340, true], ['Gulab Jamun with Rabri', 360, true], ['Shahi Tukda', 380, true]],
    ]),
  B('roof', 'The Roof Tree', 'Romantic', '🌿', 'Multi-cuisine · Rooftop',
    'Open-air rooftop dining with a breezy, relaxed feel.',
    ['Rooftop seating', 'Open sky', 'Evening lights'],
    'Smart casual', 'Take a relaxed late drive to wind down.',
    [
      [['Veg Spring Rolls', 260, true], ['Paneer Tikka', 320, true], ['Chilli Chicken', 340, false]],
      [['Cheese Garlic Naan Basket', 180, true], ['Schezwan Fried Rice', 280, true], ['Paneer Butter Masala', 340, true], ['Chicken Biryani', 380, false]],
      [['Fresh Lime Soda', 110, true], ['Virgin Mojito', 160, true], ['Cold Coffee', 170, true]],
      [['Gulab Jamun', 120, true], ['Brownie with Ice Cream', 220, true]],
    ]),
  B('bexp', 'Bhopal Express', 'Vibrant', '🚂', 'Multi-cuisine · Railway-coach dining',
    'Dine inside a restored railway coach — a quirky, fun-first evening.',
    ['Railway-coach setting', 'Novelty dining', 'Great conversation starter'],
    'Smart casual', 'A relaxed walk around the hotel grounds, then a drive by the lake.',
    [
      [['Crispy Corn', 260, true], ['Veg Platter', 360, true], ['Chicken Tikka', 420, false]],
      [['Dal Makhani', 320, true], ['Veg Biryani', 340, true], ['Paneer Lababdar', 380, true], ['Butter Chicken', 460, false]],
      [['Masala Chai', 80, true], ['Fresh Lime Soda', 120, true], ['Cold Coffee', 170, true]],
      [['Gulab Jamun', 140, true], ['Ice Cream Sundae', 220, true]],
    ]),
  B('bosc', 'Boscos (DB Mall)', 'Vibrant', '🫒', 'Mediterranean · Café',
    'Mediterranean plates in a lively mall setting.',
    ['Mediterranean menu', 'Easy mall location', 'Good for sharing'],
    'Smart casual', 'Browse the mall together or catch a movie.',
    [
      [['Falafel Bites', 320, true], ['Hummus & Pita', 340, true], ['Chicken Wings', 420, false]],
      [['Margherita Pizza', 420, true], ['Pesto Penne', 460, true], ['Grilled Chicken Plate', 580, false], ['Mezze Platter', 640, true]],
      [['Cappuccino', 160, true], ['Iced Tea', 180, true], ['Virgin Mojito', 200, true]],
      [['Tiramisu', 280, true], ['Chocolate Lava Cake', 300, true]],
    ]),
  B('thyme', 'Thyme Roof Top Restaurant', 'Vibrant', '🌇', 'Rooftop · Multi-cuisine',
    'A rooftop spot for biryani, bites and a breezy evening.',
    ['Rooftop seating', 'Biryani and bites', 'Relaxed and lively'],
    'Smart casual', 'Walk around MP Nagar to cool off after dinner.',
    [
      [['French Fries', 160, true], ['Paneer Tikka', 300, true], ['Chicken Lollipop', 360, false]],
      [['Veg Biryani', 280, true], ['Chilli Paneer', 300, true], ['Butter Naan & Dal Makhani', 320, true], ['Chicken Biryani', 340, false]],
      [['Fresh Lime Soda', 90, true], ['Cold Coffee', 140, true], ['Mango Shake', 150, true]],
      [['Ice Cream Scoop', 100, true], ['Brownie', 160, true]],
    ]),
  B('zoku', 'Cafe Zoku', 'Vibrant', '🍜', 'Asian · Café',
    'Asian-inspired plates and a stylish café vibe.',
    ['Asian flavours', 'Stylish interiors', 'Great for sharing'],
    'Smart casual', 'Pick up a dessert and stroll nearby.',
    [
      [['Crispy Chilli Baby Corn', 260, true], ['Veg Dumplings', 280, true], ['Chicken Gyoza', 340, false]],
      [['Veg Fried Rice', 280, true], ['Veg Hakka Noodles', 300, true], ['Thai Green Curry & Rice', 380, true], ['Chicken Ramen', 420, false]],
      [['Iced Tea', 160, true], ['Cold Coffee', 180, true], ['Lychee Cooler', 190, true]],
      [['Chocolate Brownie', 220, true], ['Honey Noodles with Ice Cream', 260, true]],
    ]),
  B('cent', 'Central Kafe', 'Cozy', '🛋️', 'Café · Multi-cuisine · Rooftop',
    'A F.R.I.E.N.D.S-inspired café with a cozy rooftop.',
    ['F.R.I.E.N.D.S theme', 'Rooftop dining', 'Cozy corners'],
    'Relaxed casual', 'Share a milkshake on the rooftop as the evening settles.',
    [
      [['Garlic Bread', 180, true], ['Nachos with Salsa', 240, true], ['Chicken Wings', 320, false]],
      [['Veg Burger', 240, true], ['Chicken Sandwich', 280, false], ['Pasta Alfredo', 320, true], ['Margherita Pizza', 340, true]],
      [['Cold Coffee', 150, true], ['Hot Chocolate', 170, true], ['Oreo Shake', 190, true]],
      [['Brownie', 160, true], ['Waffle with Ice Cream', 220, true]],
    ]),
  B('chino', 'Cafe Chino (Jehan Numa Palace)', 'Cozy', '🍵', 'Café · Light bites',
    'A simple, elegant café at Jehan Numa Palace.',
    ['Elegant yet simple', 'Palace setting', 'Coffee and bites'],
    'Smart casual', 'Stroll the palace gardens after your coffee.',
    [
      [['Chicken Puff', 260, false], ['Cheese Croissant', 280, true], ['Bruschetta', 320, true]],
      [['Grilled Veg Sandwich', 380, true], ['Penne Arrabbiata', 460, true], ['Chicken Club Sandwich', 480, false]],
      [['Fresh Lime Soda', 200, true], ['Cappuccino', 240, true], ['Iced Latte', 280, true]],
      [['Chocolate Pastry', 260, true], ['Cheesecake Slice', 320, true]],
    ]),
  B('momo', 'Momo Cafe (Marriott Bhopal)', 'Cozy', '🥐', 'Café · All-day dining',
    'An upscale hotel café for relaxed all-day dining.',
    ['Hotel café', 'Calm and upscale', 'All-day menu'],
    'Smart casual', 'A quiet drive around the city’s lakes.',
    [
      [['Soup of the Day', 360, true], ['Bruschetta', 420, true], ['Chicken Satay', 520, false]],
      [['Veg Pasta', 560, true], ['Club Sandwich', 620, false], ['Thai Curry & Rice', 680, true], ['Grilled Fish & Greens', 820, false]],
      [['Iced Tea', 240, true], ['Cappuccino', 260, true], ['Fresh Juice', 280, true]],
      [['Chocolate Cake', 360, true], ['New York Cheesecake', 380, true]],
    ]),
  B('bapu', 'Bapu Ki Kutia', 'Casual', '🍛', 'Vegetarian · Thali',
    'Classic vegetarian thalis — a TT Nagar family favourite since 1964.',
    ['Since 1964', 'Traditional thali', 'Pocket-friendly'],
    'Comfortable casual', 'A relaxed walk, or a sweet from a nearby mithai shop.',
    [
      [['Samosa', 60, true], ['Dahi Vada', 120, true], ['Paneer Pakoda', 160, true]],
      [['Mixed Veg & Paratha', 200, true], ['Paneer Butter Masala & Roti', 260, true], ['Dal Baati', 260, true], ['Special Thali', 280, true]],
      [['Masala Chai', 30, true], ['Chaas', 40, true], ['Sweet Lassi', 70, true]],
      [['Gulab Jamun', 70, true], ['Moong Dal Halwa', 100, true]],
    ]),
  B('caff', 'Caffeine Mug Cafe', 'Casual', '☕', 'Café · Snacks',
    'A budget-friendly Habib Ganj café — coffee and snacks for two.',
    ['Very affordable', 'Easy and relaxed', 'Great first meet-up'],
    'Casual', 'Take a relaxed walk around the area.',
    [
      [['Veg Sandwich', 60, true], ['French Fries', 70, true], ['Garlic Bread', 80, true]],
      [['Maggi', 60, true], ['Veg Burger', 80, true], ['Cheese Sandwich', 90, true], ['Pasta', 110, true]],
      [['Masala Tea', 20, true], ['Hot Coffee', 30, true], ['Cold Coffee', 50, true]],
      [['Ice Cream', 50, true], ['Brownie', 60, true]],
    ]),
]
