/* Sample venues for India's metro cities. Venue names are real places; descriptions, menus and
   prices are ILLUSTRATIVE — hours, menus and prices change, so always confirm with the venue. */
import { makeVenue as V } from '../venueHelpers'

export const METRO_VENUES = [
  /* ------------------------------ Delhi ------------------------------ */
  V('delhi', 'dl-ia', 'Indian Accent', 'Romantic', '🥂', 'Modern Indian · Fine dining',
    'Inventive modern Indian cooking for a milestone evening.',
    ['Chef-led tasting menus', 'Elegant setting', 'Special occasions'],
    'Smart formal', 'A quiet evening stroll in Lodhi Garden.',
    [
      [['Chef’s Amuse-Bouche Trio', 650, true], ['Seasonal Chaat Course', 850, true], ['Tandoori Prawn Course', 1250, false]],
      [['A La Carte Main of the Day (veg)', 1650, true], ['A La Carte Main of the Day', 1950, false], ['Vegetarian Tasting Menu (per person)', 4900, true, 'Multi-course, chef’s selection'], ['Tasting Menu with Meat & Seafood (per person)', 5600, false]],
      [['Signature Mocktail', 550, true], ['Sparkling Water', 400, true], ['House Wine (glass)', 900, true, '', true]],
      [['Chef’s Dessert Course', 900, true], ['Petit Fours & Coffee', 650, true]],
    ]),
  V('delhi', 'dl-bc', 'Big Chill Cafe', 'Cozy', '🍝', 'Café · Italian · Desserts',
    'A Khan Market favourite for pasta, pizza and dessert.',
    ['Great desserts', 'Busy, buzzy corners', 'Reliable comfort food'],
    'Smart casual', 'Browse the lanes of Khan Market and share one last dessert.',
    [
      [['Garlic Bread with Cheese', 320, true], ['Bruschetta', 380, true], ['Peri-Peri Chicken Wings', 450, false]],
      [['Penne Arrabbiata', 520, true], ['Wild Mushroom Pizza', 620, true], ['Chicken Lasagna', 680, false]],
      [['Cold Coffee', 280, true], ['Fresh Lime Soda', 200, true], ['Hot Chocolate', 300, true]],
      [['Mississippi Mud Pie', 420, true], ['Tiramisu', 420, true]],
    ]),
  V('delhi', 'dl-soc', 'Social (Hauz Khas Village)', 'Vibrant', '🎧', 'Global bites · Bar',
    'A buzzing hangout — work-by-day, party-by-night.',
    ['Lively crowd', 'Great cocktails', 'Playlists and energy'],
    'Casual chic', 'Wander the lanes of Hauz Khas Village.',
    [
      [['Chilli Cheese Toast', 350, true], ['Dahi Ke Sholay', 420, true], ['Chicken Tikka Bites', 480, false]],
      [['Pesto Pasta', 520, true], ['Margherita Pizza', 560, true], ['Butter Chicken & Naan', 620, false]],
      [['Virgin Mojito', 320, true], ['Craft Beer (pint)', 450, true, '', true], ['Cocktail of the Day', 620, true, '', true]],
      [['Brownie with Ice Cream', 380, true], ['Cheesecake', 420, true]],
    ]),
  V('delhi', 'dl-kar', 'Karim’s', 'Casual', '🍢', 'Mughlai · Kebabs',
    'Legendary Old Delhi Mughlai, close to Jama Masjid.',
    ['Old Delhi heritage', 'Kebabs and curries', 'Pocket-friendly'],
    'Comfortable casual', 'Walk the lanes near Jama Masjid, then try a street dessert.',
    [
      [['Paneer Tikka', 240, true], ['Seekh Kebab', 260, false], ['Chicken Jahangiri', 320, false], ['Mutton Burra', 380, false]],
      [['Dal Fry & Roti', 180, true], ['Chicken Stew', 300, false], ['Mutton Korma', 360, false]],
      [['Masala Soda', 70, true], ['Sweet Lassi', 90, true], ['Cold Drink', 60, true]],
      [['Phirni', 90, true], ['Shahi Tukda', 120, true]],
    ]),

  /* ------------------------------ Mumbai ----------------------------- */
  V('mumbai', 'mb-pbb', 'Pizza by the Bay', 'Romantic', '🌊', 'Italian · Pizza · Sea view',
    'Sea-facing tables on Marine Drive.',
    ['Sea views', 'Sunset tables', 'Easy and romantic'],
    'Smart casual, light layers', 'Walk the Marine Drive promenade as the city lights come on.',
    [
      [['Garlic Bread', 320, true], ['Bruschetta', 390, true], ['Crispy Calamari', 560, false]],
      [['Margherita Pizza', 520, true], ['Pasta Alfredo', 560, true], ['Pepperoni Pizza', 640, false]],
      [['Iced Tea', 240, true], ['Virgin Mojito', 280, true], ['Sangria (glass)', 520, true, '', true]],
      [['Chocolate Brownie', 320, true], ['Tiramisu', 380, true]],
    ]),
  V('mumbai', 'mb-kgc', 'Kala Ghoda Café', 'Cozy', '☕', 'Café · Brunch · Coffee',
    'A relaxed art-district café for coffee and slow brunches.',
    ['Art district', 'Great coffee', 'Slow brunches'],
    'Relaxed smart casual', 'Explore the Kala Ghoda art lanes and galleries.',
    [
      [['Avocado Toast', 420, true], ['Hummus & Pita', 380, true], ['Egg Toast Trio', 360, false]],
      [['Pesto Sandwich', 420, true], ['Grilled Chicken Sandwich', 480, false], ['Eggs Benedict', 520, false]],
      [['Filter Coffee', 180, true], ['Flat White', 240, true], ['Iced Latte', 260, true]],
      [['Chocolate Cake', 320, true], ['Banoffee Pie', 340, true]],
    ]),
  V('mumbai', 'mb-leo', 'Leopold Cafe', 'Vibrant', '🍺', 'Multi-cuisine · Colaba',
    'A Colaba institution with a lively, buzzing crowd.',
    ['Iconic Colaba spot', 'Lively atmosphere', 'Cold beer & big plates'],
    'Casual, comfortable', 'Stroll over to the Gateway of India promenade.',
    [
      [['Chilli Cheese Toast', 280, true], ['Chicken Tikka', 420, false], ['Prawn Koliwada', 560, false]],
      [['Veg Biryani', 420, true], ['Butter Chicken & Naan', 520, false], ['Chicken Sizzler', 620, false]],
      [['Fresh Lime Soda', 160, true], ['Cold Coffee', 220, true], ['Draught Beer (pint)', 380, true, '', true]],
      [['Gulab Jamun', 180, true], ['Brownie Sundae', 320, true]],
    ]),
  V('mumbai', 'mb-brit', 'Britannia & Co.', 'Casual', '🍚', 'Parsi · Iranian café',
    'A heritage Parsi café famous for its berry pulao.',
    ['Heritage café', 'Parsi classics', 'Old-school charm'],
    'Comfortable casual', 'Wander around the heritage buildings of the Fort area.',
    [
      [['Veg Cutlets', 220, true], ['Kheema Pav', 280, false], ['Chicken Cutlet', 280, false]],
      [['Veg Berry Pulao', 520, true], ['Sali Boti', 620, false], ['Berry Pulao (Chicken)', 680, false]],
      [['Lemon Soda', 110, true], ['Raspberry Soda', 140, true], ['Irani Chai', 90, true]],
      [['Caramel Custard', 180, true], ['Lagan Nu Custard', 200, true]],
    ]),

  /* ----------------------------- Bengaluru --------------------------- */
  V('bengaluru', 'bl-kar', 'Karavalli', 'Romantic', '🦐', 'Coastal · Fine dining',
    'Elegant coastal-India dining in a garden setting.',
    ['Coastal specialities', 'Garden ambience', 'Special occasions'],
    'Smart formal', 'A calm drive through the tree-lined avenues nearby.',
    [
      [['Tender Coconut Kebab', 620, true], ['Crispy Calamari', 720, false], ['Pepper Prawns', 880, false]],
      [['Appam with Vegetable Stew', 780, true], ['Malabar Chicken Curry', 980, false], ['Konkani Fish Curry', 1150, false]],
      [['Fresh Lime Soda', 280, true], ['Tender Coconut Cooler', 320, true], ['House Wine (glass)', 780, true, '', true]],
      [['Elaneer Payasam', 420, true], ['Chocolate Fondant', 520, true]],
    ]),
  V('bengaluru', 'bl-hitw', 'The Hole in the Wall Cafe', 'Cozy', '🥞', 'Café · All-day breakfast',
    'A tiny, much-loved Koramangala café for brunch.',
    ['All-day breakfast', 'Small and snug', 'Great pancakes'],
    'Relaxed casual', 'Walk around Koramangala and pick up a dessert to share.',
    [
      [['Hash Browns', 260, true], ['Cheesy Garlic Toast', 280, true], ['Chicken Sausage Bites', 340, false]],
      [['Pancake Stack', 380, true], ['Loaded Omelette', 360, false], ['Chicken Sandwich', 420, false]],
      [['Filter Coffee', 140, true], ['Fresh Orange Juice', 200, true], ['Cold Brew', 220, true]],
      [['Brownie', 260, true], ['Waffle with Ice Cream', 340, true]],
    ]),
  V('bengaluru', 'bl-toit', 'Toit Brewpub', 'Vibrant', '🍻', 'Brewpub · Pizza',
    'Indiranagar’s much-loved craft-beer brewpub.',
    ['Craft beer', 'Wood-fired pizza', 'Lively crowd'],
    'Smart casual', 'Take a late walk along Indiranagar’s 100 Feet Road.',
    [
      [['Peri-Peri Fries', 320, true], ['Garlic Cheese Bread', 360, true], ['Chicken Wings', 520, false]],
      [['Pasta Aglio e Olio', 560, true], ['Margherita Pizza', 620, true], ['Pepperoni Pizza', 720, false]],
      [['Ginger Lemonade', 240, true], ['Virgin Mojito', 280, true], ['Craft Beer (pint)', 460, true, '', true]],
      [['Chocolate Brownie', 340, true], ['Cheesecake', 380, true]],
    ]),
  V('bengaluru', 'bl-vid', 'Vidyarthi Bhavan', 'Casual', '🥘', 'South Indian · Dosas',
    'A Basavanagudi classic, famous for its masala dosa.',
    ['Famous masala dosa', 'Heritage eatery', 'Best for a morning or lunch date'],
    'Comfortable casual', 'Stroll around Gandhi Bazaar for filter coffee.',
    [
      [['Medu Vada', 70, true], ['Idli Vada', 90, true], ['Rava Idli', 100, true]],
      [['Khara Bath', 90, true], ['Set Dosa', 100, true], ['Masala Dosa', 110, true]],
      [['Tea', 30, true], ['Filter Coffee', 40, true], ['Lassi', 60, true]],
      [['Kesari Bath', 70, true], ['Payasam', 80, true]],
    ]),

  /* ----------------------------- Hyderabad --------------------------- */
  V('hyderabad', 'hy-adaa', 'Adaa (Taj Falaknuma Palace)', 'Romantic', '🏰', 'Nizami · Fine dining',
    'Royal Hyderabadi dining inside a palace hotel.',
    ['Palace setting', 'Nizami cuisine', 'Milestone evenings'],
    'Smart formal', 'Enjoy the hilltop views from the palace terraces.',
    [
      [['Dahi Ke Kebab', 980, true], ['Haleem Tartlet', 1050, false], ['Shikampuri Kebab', 1150, false]],
      [['Mirchi Ka Salan & Rumali Roti', 1250, true], ['Veg Dum Biryani', 1450, true], ['Hyderabadi Dum Biryani', 1650, false]],
      [['Sparkling Water', 420, true], ['Rose Sharbat', 450, true], ['Fresh Juice', 480, true]],
      [['Double Ka Meetha', 650, true], ['Qubani Ka Meetha', 650, true]],
    ]),
  V('hyderabad', 'hy-nim', 'Nimrah Café & Bakery', 'Cozy', '☕', 'Irani chai · Bakery',
    'Irani chai with Osmania biscuits, near Charminar.',
    ['Irani chai', 'Charminar area', 'Old Hyderabad charm'],
    'Comfortable casual', 'Walk around the Charminar area and its bangle bazaars.',
    [
      [['Osmania Biscuits (plate)', 60, true], ['Samosa', 50, true], ['Veg Puff', 60, true]],
      [['Bun Maska', 70, true], ['Keema Samosa', 120, false], ['Chicken Sandwich', 160, false]],
      [['Irani Chai', 40, true], ['Lemon Tea', 50, true], ['Cold Coffee', 120, true]],
      [['Pastry', 90, true], ['Sheer Khurma', 120, true]],
    ]),
  V('hyderabad', 'hy-prost', 'Prost Brew Pub', 'Vibrant', '🍺', 'Brewpub · Continental',
    'A lively craft-beer brewpub for sharing plates and music.',
    ['Craft beer', 'Sharing plates', 'Lively evenings'],
    'Smart casual', 'Drive past the lit-up Hussain Sagar lakefront.',
    [
      [['Cheese Garlic Bread', 350, true], ['Nachos', 420, true], ['Chicken Wings', 520, false]],
      [['Margherita Pizza', 560, true], ['Pasta Alfredo', 580, true], ['Grilled Chicken with Fries', 680, false]],
      [['Iced Tea', 240, true], ['Mojito', 320, true], ['Craft Beer (pint)', 480, true, '', true]],
      [['Cheesecake', 400, true], ['Brownie Sizzler', 420, true]],
    ]),
  V('hyderabad', 'hy-par', 'Paradise Biryani', 'Casual', '🍛', 'Hyderabadi · Biryani',
    'The biryani Hyderabad swears by.',
    ['Iconic biryani', 'Quick and filling', 'Great value'],
    'Comfortable casual', 'Pick up a Hyderabadi dessert and take a short walk.',
    [
      [['Veg Manchurian', 260, true], ['Chicken 65', 320, false], ['Mutton Seekh', 380, false]],
      [['Veg Biryani', 320, true], ['Chicken Biryani', 380, false], ['Mutton Biryani', 480, false]],
      [['Cold Drink', 60, true], ['Fresh Lime Soda', 90, true], ['Sweet Lassi', 110, true]],
      [['Phirni', 130, true], ['Double Ka Meetha', 150, true]],
    ]),

  /* ------------------------------ Chennai ---------------------------- */
  V('chennai', 'ch-dak', 'Dakshin (ITC Grand Chola)', 'Romantic', '🪔', 'South Indian · Fine dining',
    'Refined regional South Indian dining.',
    ['Regional specialities', 'Fine dining', 'Special occasions'],
    'Smart formal', 'A quiet evening drive along the city’s leafy avenues.',
    [
      [['Banana Blossom Cutlets', 560, true], ['Mini Idli Sambar Shots', 620, true], ['Chettinad Crab Cakes', 880, false]],
      [['Kerala Vegetable Stew with Appam', 820, true], ['Chettinad Chicken Curry', 980, false], ['Malabar Fish Curry', 1100, false]],
      [['Filter Coffee', 280, true], ['Tender Coconut Water', 300, true], ['Rose Lemonade', 320, true]],
      [['Elaneer Payasam', 480, true], ['Payasam Trio', 520, true]],
    ]),
  V('chennai', 'ch-ame', 'Amethyst', 'Cozy', '🌿', 'Café · Garden · Continental',
    'A heritage-bungalow café with a leafy garden in Royapettah.',
    ['Garden seating', 'Heritage bungalow', 'Quiet and cozy'],
    'Relaxed smart casual', 'Take a walk along Marina Beach as the day cools.',
    [
      [['Garlic Bread', 320, true], ['Mushroom Bruschetta', 380, true], ['Chicken Croquettes', 420, false]],
      [['Veg Quiche & Salad', 480, true], ['Penne Pesto', 520, true], ['Herb Grilled Chicken', 620, false]],
      [['Fresh Lime Soda', 180, true], ['Iced Tea', 220, true], ['Cold Coffee', 240, true]],
      [['Walnut Brownie', 320, true], ['Lemon Tart', 340, true]],
    ]),
  V('chennai', 'ch-bn', 'Barbeque Nation', 'Vibrant', '🔥', 'BBQ · Grill buffet',
    'Live grills at your table — fun from the first skewer.',
    ['Interactive grill', 'Unlimited feast', 'Playful and social'],
    'Casual and comfortable', 'Walk off the feast along Besant Nagar beach.',
    [
      [['Crispy Corn Basket', 240, true], ['Peri-Peri Paneer Bites', 310, true], ['Chicken Wings Basket', 360, false]],
      [['Veg Grill Buffet (per person)', 899, true, 'Unlimited live grills, mains and desserts'], ['Non-Veg Grill Buffet (per person)', 1099, false], ['Premium Buffet (per person)', 1349, false, 'Adds seafood and lamb grills']],
      [['Fresh Lime Soda', 120, true], ['Mango Lassi', 160, true], ['Mocktail of the Day', 210, true]],
      [['Gulab Jamun', 130, true], ['Ice Cream Duo', 170, true]],
    ]),
  V('chennai', 'ch-mur', 'Murugan Idli Shop', 'Casual', '🍽️', 'South Indian · Idli',
    'Soft idlis with a spread of chutneys.',
    ['Famous idlis', 'Quick and cheap', 'Comfort food'],
    'Comfortable casual', 'Grab a filter coffee and take a seaside walk.',
    [
      [['Medu Vada', 70, true], ['Mini Idli', 90, true], ['Onion Pakoda', 90, true]],
      [['Idli Sambar (3 pc)', 90, true], ['Ghee Pongal', 110, true], ['Masala Dosa', 120, true]],
      [['Tea', 30, true], ['Buttermilk', 40, true], ['Filter Coffee', 40, true]],
      [['Kesari', 60, true], ['Payasam', 70, true]],
    ]),

  /* ------------------------------ Kolkata ---------------------------- */
  V('kolkata', 'kl-moc', 'Mocambo', 'Romantic', '🍷', 'Continental · Park Street',
    'A retro Park Street dining room with old-world charm.',
    ['Retro Park Street', 'Old-world ambience', 'Classic continental'],
    'Smart casual to formal', 'A stroll down illuminated Park Street.',
    [
      [['Cheese Balls', 380, true], ['Chicken Cutlet', 420, false], ['Prawn Cocktail', 680, false]],
      [['Veg Au Gratin', 560, true], ['Chicken Kiev', 720, false], ['Fish Meunière', 780, false]],
      [['Fresh Lime Soda', 160, true], ['Virgin Mojito', 280, true], ['House Wine (glass)', 480, true, '', true]],
      [['Caramel Custard', 260, true], ['Baked Alaska', 420, true]],
    ]),
  V('kolkata', 'kl-flu', 'Flurys', 'Cozy', '🧁', 'Tearoom · Bakery',
    'A Park Street tearoom famed for pastries and breakfast.',
    ['Classic tearoom', 'Pastries and cakes', 'Colonial-era charm'],
    'Smart casual', 'Walk down Park Street and pick up pastries to go.',
    [
      [['Veg Puff', 150, true], ['Chicken Patty', 180, false], ['Cheese Toast', 220, true]],
      [['Veg Grilled Sandwich', 340, true], ['Club Sandwich', 420, false], ['Chicken Quiche', 460, false]],
      [['Cold Coffee', 240, true], ['Darjeeling Tea (pot)', 260, true], ['Hot Chocolate', 280, true]],
      [['Rum Ball', 160, true], ['Chocolate Pastry', 220, true]],
    ]),
  V('kolkata', 'kl-pc', 'Peter Cat', 'Vibrant', '🍢', 'Continental · Mughlai',
    'A Park Street favourite known for its chelo kebab.',
    ['Famous chelo kebab', 'Lively dining room', 'Park Street classic'],
    'Smart casual', 'Walk Park Street and watch the city lights.',
    [
      [['Chicken Cutlet', 360, false], ['Paneer Tikka', 380, true], ['Fish Fry', 420, false]],
      [['Veg Chelo Platter', 520, true], ['Chelo Kebab', 620, false], ['Chicken Sizzler', 640, false]],
      [['Fresh Lime Soda', 160, true], ['Cold Coffee', 220, true], ['Mocktail', 260, true]],
      [['Mishti Doi', 140, true], ['Brownie Sizzler', 380, true]],
    ]),
  V('kolkata', 'kl-ich', 'Indian Coffee House (College Street)', 'Casual', '📚', 'Coffee · Snacks',
    'The legendary College Street adda over coffee.',
    ['Historic adda spot', 'Cheap and cheerful', 'A book-lover’s haunt'],
    'Relaxed casual', 'Browse the College Street book stalls.',
    [
      [['Veg Chop', 90, true], ['Fish Fry', 140, false], ['Chicken Pakora', 150, false]],
      [['Veg Sandwich', 100, true], ['Mughlai Paratha', 160, false], ['Chicken Afghani', 180, false]],
      [['Tea', 30, true], ['Infusion Coffee', 60, true], ['Cold Coffee', 90, true]],
      [['Mishti Doi', 70, true], ['Ice Cream', 80, true]],
    ]),

  /* ------------------------------- Pune ------------------------------ */
  V('pune', 'pn-mal', 'Malaka Spice', 'Romantic', '🏮', 'Pan-Asian',
    'Garden-style pan-Asian dining in Koregaon Park.',
    ['Garden-style setting', 'Pan-Asian menu', 'Candlelit evenings'],
    'Smart casual', 'A relaxed walk around the lanes of Koregaon Park.',
    [
      [['Vegetable Spring Rolls', 380, true], ['Crispy Corn Salt & Pepper', 420, true], ['Chicken Satay', 520, false]],
      [['Pad Thai Noodles', 580, true], ['Thai Green Curry with Rice', 620, true], ['Burmese Khow Suey', 620, false]],
      [['Fresh Lime Soda', 200, true], ['Iced Tea', 240, true], ['Lemongrass Cooler', 260, true]],
      [['Tender Coconut Pudding', 380, true], ['Chocolate Fondant', 420, true]],
    ]),
  V('pune', 'pn-gb', 'German Bakery', 'Cozy', '🥐', 'Bakery · Café',
    'A Koregaon Park café-bakery with a relaxed vibe.',
    ['Fresh bakes', 'Relaxed vibe', 'Easy brunch'],
    'Relaxed casual', 'Stroll through the nearby lanes of Koregaon Park.',
    [
      [['Chicken Puff', 200, false], ['Garlic Bread', 220, true], ['Cheese Croissant', 240, true]],
      [['Veg Sandwich', 320, true], ['Chicken Burger', 420, false], ['Pasta Alfredo', 420, true]],
      [['Cappuccino', 180, true], ['Iced Tea', 200, true], ['Cold Coffee', 220, true]],
      [['Brownie', 200, true], ['Cheesecake Slice', 260, true]],
    ]),
  V('pune', 'pn-eff', 'Effingut Brewerks', 'Vibrant', '🍺', 'Brewpub',
    'A lively craft-brew spot for beers and sharing plates.',
    ['Craft beer', 'Lively crowd', 'Sharing plates'],
    'Smart casual', 'Head for a late dessert stop nearby.',
    [
      [['Cheesy Fries', 340, true], ['Loaded Nachos', 420, true], ['Chicken Wings', 520, false]],
      [['Pasta Arrabbiata', 540, true], ['Margherita Pizza', 560, true], ['BBQ Chicken Pizza', 680, false]],
      [['Iced Tea', 220, true], ['Virgin Mojito', 260, true], ['Craft Beer (pint)', 450, true, '', true]],
      [['Brownie Sundae', 360, true], ['Cheesecake', 380, true]],
    ]),
  V('pune', 'pn-vai', 'Vaishali', 'Casual', '🥞', 'South Indian · Snacks',
    'An FC Road institution for dosas and filter coffee.',
    ['FC Road institution', 'Dosas and snacks', 'Student-friendly prices'],
    'Comfortable casual', 'Walk along FC Road and grab something sweet.',
    [
      [['Medu Vada', 90, true], ['Idli Sambar', 90, true], ['Misal Pav', 120, true]],
      [['Masala Dosa', 140, true], ['Uttapam', 140, true], ['Cheese Dosa', 170, true]],
      [['Tea', 30, true], ['Filter Coffee', 50, true], ['Lassi', 90, true]],
      [['Sheera', 80, true], ['Gulab Jamun', 80, true]],
    ]),
]
