/* Venues for Indore, Jabalpur, Ahmedabad, Jaipur, Lucknow, Chandigarh, Nagpur and Kochi.
   Names are real places (cafes, restaurants and street-food spots); descriptions, menus and prices are
   ILLUSTRATIVE — hours, menus and prices change, so always confirm with the venue.
   kind: 'cafe' | 'restaurant' | 'street' */
import { makeVenue } from '../venueHelpers'

const T = true
const F = false
const make = (city) => (kind, ...args) => ({ ...makeVenue(city, ...args), kind })

const indore = make('indore')
const jabalpur = make('jabalpur')
const ahmedabad = make('ahmedabad')
const jaipur = make('jaipur')
const lucknow = make('lucknow')
const chandigarh = make('chandigarh')
const nagpur = make('nagpur')
const kochi = make('kochi')

export const TIER2_VENUES = [
  /* ------------------------------ Indore ----------------------------- */
  indore('cafe', 'in-mrb', 'Mr. Beans', 'Cozy', '☕', 'Café · French & Italian',
    'A relaxed café known for its French and Italian menu.',
    ['Relaxed ambience', 'French & Italian menu', 'Great for couples'],
    'Smart casual', 'Take an easy evening stroll nearby.',
    [
      [['Garlic Bread', 180, T], ['Peri-Peri Fries', 190, T], ['Bruschetta', 220, T]],
      [['Penne Alfredo', 320, T], ['Margherita Pizza', 340, T], ['Croque Monsieur', 360, T], ['Chicken Pesto Pasta', 380, F]],
      [['Cappuccino', 160, T], ['Cold Coffee', 180, T], ['Hot Chocolate', 190, T]],
      [['Tiramisu', 240, T], ['Waffle with Ice Cream', 260, T]],
    ]),
  indore('cafe', 'in-mang', 'Mangosteen Café', 'Cozy', '🌿', 'Café · Rooftop',
    'A charming rooftop-themed chill-out café in New Palasia.',
    ['Rooftop theme', 'Great seating', 'Easy, chilled vibe'],
    'Relaxed casual', 'Walk around New Palasia after your coffee.',
    [
      [['Nachos with Salsa', 220, T], ['Garlic Bread', 170, T], ['Chicken Wings', 320, F]],
      [['Veg Burger', 240, T], ['Pasta Alfredo', 320, T], ['Paneer Tikka Pizza', 360, T], ['Chicken Sandwich', 300, F]],
      [['Cold Coffee', 150, T], ['Virgin Mojito', 170, T], ['Oreo Shake', 190, T]],
      [['Brownie with Ice Cream', 200, T], ['Waffle', 180, T]],
    ]),
  indore('cafe', 'in-monk', 'Little Monk Café', 'Cozy', '🍃', 'Café · Continental',
    'A calm café for coffee and unhurried conversation.',
    ['Calm and quiet', 'Good coffee', 'Easy first meet-up'],
    'Relaxed casual', 'Take a slow walk and share a dessert.',
    [
      [['Cheese Garlic Toast', 170, T], ['Hummus & Pita', 260, T], ['French Fries', 150, T]],
      [['Grilled Sandwich', 240, T], ['White Sauce Pasta', 320, T], ['Margherita Pizza', 330, T]],
      [['Filter Coffee', 120, T], ['Iced Tea', 160, T], ['Cold Coffee', 170, T]],
      [['Chocolate Brownie', 190, T], ['Cheesecake Slice', 240, T]],
    ]),
  indore('cafe', 'in-kyro', 'Kyro Café', 'Vibrant', '🎶', 'Café · Multi-cuisine',
    'A lively café with a modern, social feel.',
    ['Social atmosphere', 'Wide menu', 'Good for groups and dates'],
    'Smart casual', 'Walk off dinner with a stroll nearby.',
    [
      [['Cheesy Nachos', 240, T], ['Crispy Corn', 220, T], ['Chicken Popcorn', 280, F]],
      [['Pasta Arrabbiata', 320, T], ['Veg Burger', 250, T], ['Paneer Tikka Roll', 260, T], ['Chicken Burger', 300, F]],
      [['Cold Coffee', 160, T], ['Blue Lagoon', 180, T], ['Mojito', 180, T]],
      [['Brownie', 190, T], ['Ice Cream Sundae', 210, T]],
    ]),
  indore('street', 'in-sarafa', 'Sarafa Bazaar (night food market)', 'Vibrant', '🌙', 'Street food · Night market',
    'A jewellery market by day that becomes Indore’s legendary street-food lane after 9 pm.',
    ['Comes alive after 9 pm', 'Jalebi, kachori and more', 'An Indore institution'],
    'Casual, comfortable shoes', 'Walk the lit-up lanes and pick a few last bites.',
    [
      [['Dahi Vada', 70, T], ['Kachori', 50, T], ['Bhutte Ka Kees', 60, T]],
      [['Garadu (fried yam)', 90, T], ['Sabudana Khichdi', 70, T], ['Pav Bhaji', 90, T], ['Chaat Plate', 100, T]],
      [['Masala Chai', 20, T], ['Sweet Lassi', 50, T], ['Cold Coffee', 60, T]],
      [['Malpua', 60, T], ['Jalebi with Rabri', 70, T], ['Gulab Jamun', 50, T]],
    ]),
  indore('street', 'in-chappan', 'Chappan Dukan (56 Dukan)', 'Casual', '🍬', 'Street food · Snacks & sweets',
    'Fifty-six snack shops, open by day — Indore’s famous food street.',
    ['Dozens of food stalls', 'Open in the daytime', 'Snacks, sweets and meals'],
    'Comfortable casual', 'Browse the stalls for sweets to take home.',
    [
      [['Samosa Kachori', 40, T], ['Aloo Tikki', 60, T], ['Dahi Vada', 70, T]],
      [['Chole Kulche', 80, T], ['Veg Sandwich', 90, T], ['Pav Bhaji', 100, T], ['Dal Bafla', 130, T]],
      [['Masala Chai', 20, T], ['Sugarcane Juice', 40, T], ['Sweet Lassi', 50, T]],
      [['Jalebi', 60, T], ['Malpua', 70, T], ['Rasmalai', 80, T]],
    ]),
  indore('street', 'in-vijay', 'Vijay Chaat House', 'Casual', '🥔', 'Chaat · Snacks',
    'Known for its khopra patties and matar kachori.',
    ['Khopra patties', 'Matar kachori', 'Quick and tasty'],
    'Comfortable casual', 'Finish with a sweet from a nearby shop.',
    [
      [['Samosa', 40, T], ['Matar Kachori', 50, T], ['Khopra Patties', 60, T]],
      [['Pani Puri', 50, T], ['Aloo Tikki Chaat', 90, T], ['Chaat Platter', 120, T]],
      [['Buttermilk', 30, T], ['Masala Chai', 20, T], ['Sweet Lassi', 50, T]],
      [['Kulfi', 70, T], ['Jalebi', 60, T]],
    ]),
  indore('restaurant', 'in-madhuram', 'Madhuram Sweets', 'Casual', '🍮', 'Sweets · Snacks',
    'A sweet shop loved for its ras malai and fresh snacks.',
    ['Ras malai', 'Fresh snacks', 'Sweet-tooth friendly'],
    'Comfortable casual', 'Take a box of sweets for the walk home.',
    [
      [['Samosa', 40, T], ['Kachori', 45, T], ['Dhokla', 60, T]],
      [['Poori Sabzi', 90, T], ['Chole Bhature', 110, T], ['Paneer Paratha', 120, T]],
      [['Masala Chai', 25, T], ['Sweet Lassi', 60, T], ['Badam Milk', 70, T]],
      [['Gulab Jamun', 60, T], ['Ras Malai', 90, T], ['Kaju Katli (100 g)', 110, T]],
    ]),
  indore('restaurant', 'in-bapu', 'Bapu Ki Kutia (Indore)', 'Casual', '🍛', 'Indian · Vegetarian',
    'A well-loved vegetarian spot for comforting Indian meals.',
    ['Vegetarian', 'Comfort food', 'Pocket-friendly'],
    'Comfortable casual', 'A relaxed walk or a sweet nearby.',
    [
      [['Samosa', 50, T], ['Dahi Vada', 100, T], ['Paneer Pakoda', 150, T]],
      [['Mixed Veg & Paratha', 190, T], ['Paneer Butter Masala & Roti', 250, T], ['Dal Baati', 250, T], ['Special Thali', 280, T]],
      [['Masala Chai', 30, T], ['Chaas', 40, T], ['Sweet Lassi', 70, T]],
      [['Gulab Jamun', 70, T], ['Moong Dal Halwa', 100, T]],
    ]),

  /* ----------------------------- Jabalpur ---------------------------- */
  jabalpur('cafe', 'jb-smoky', 'Smoky Brew', 'Vibrant', '🔥', 'Café · Chinese · Italian · North Indian',
    'A popular hangout (since 2018) for Chinese, Italian and North Indian plates.',
    ['Wide menu', 'Locals’ favourite', 'Great with friends or a date'],
    'Smart casual', 'Take an evening drive around the city.',
    [
      [['Veg Spring Rolls', 200, T], ['Chilli Paneer', 260, T], ['Chicken Lollipop', 300, F]],
      [['Hakka Noodles', 240, T], ['Penne Arrabbiata', 280, T], ['Paneer Butter Masala & Naan', 320, T], ['Chicken Biryani', 340, F]],
      [['Cold Coffee', 140, T], ['Virgin Mojito', 150, T], ['Lemon Iced Tea', 130, T]],
      [['Brownie with Ice Cream', 180, T], ['Sizzling Brownie', 220, T]],
    ]),
  jabalpur('cafe', 'jb-koyla', 'Koyla Cafe', 'Vibrant', '🎧', 'Café · Music · Multi-cuisine',
    'A lively café with a DJ and a party feel.',
    ['DJ music', 'Lively crowd', 'Fun evenings'],
    'Smart casual', 'Keep the evening going with a night drive.',
    [
      [['Peri-Peri Fries', 170, T], ['Nachos', 210, T], ['Chicken Wings', 290, F]],
      [['White Sauce Pasta', 280, T], ['Veg Pizza', 300, T], ['Paneer Tikka Roll', 240, T], ['Chicken Burger', 280, F]],
      [['Cold Coffee', 150, T], ['Blue Lagoon', 170, T], ['Oreo Shake', 180, T]],
      [['Brownie', 170, T], ['Ice Cream Sundae', 200, T]],
    ]),
  jabalpur('cafe', 'jb-nbc', 'Nothing Before Coffee', 'Cozy', '☕', 'Coffee · Cold brews · Specialty drinks',
    'Specialty coffee, cold brews and an Instagram-friendly, cozy café.',
    ['100+ beverages', 'Cold brews', 'Free Wi-Fi'],
    'Relaxed casual', 'Walk around nearby with a cold brew to go.',
    [
      [['Garlic Bread', 160, T], ['Cheese Fries', 170, T], ['Loaded Nachos', 220, T]],
      [['Grilled Sandwich', 200, T], ['Veg Burger', 220, T], ['Pasta Alfredo', 290, T]],
      [['Signature Latte', 170, T], ['Cold Brew', 190, T], ['Lotus Biscoff Shake', 230, T], ['Iced Coffee', 150, T]],
      [['Biscoff Cheesecake', 240, T], ['Brownie', 170, T]],
    ]),
  jabalpur('cafe', 'jb-ich', 'Indian Coffee House (Jabalpur)', 'Cozy', '📚', 'Coffee · Indian · Chinese',
    'Regal interiors and good filter coffee — a Jabalpur classic.',
    ['Atmospheric interiors', 'Filter coffee', 'Paneer bhurji with hot rotis'],
    'Relaxed casual', 'Stroll nearby after your coffee.',
    [
      [['Veg Cutlet', 90, T], ['Onion Pakoda', 80, T], ['French Fries', 100, T]],
      [['Paneer Bhurji & Roti', 180, T], ['Masala Dosa', 120, T], ['Veg Fried Rice', 140, T], ['Chicken Biryani', 220, F]],
      [['Tea', 30, T], ['Filter Coffee', 50, T], ['Cold Coffee', 90, T]],
      [['Ice Cream', 80, T], ['Gulab Jamun', 70, T]],
    ]),
  jabalpur('restaurant', 'jb-arihant', 'Arihant Palace', 'Romantic', '🏛️', 'Multi-cuisine · Dining',
    'A well-known sit-down restaurant for a special dinner.',
    ['Sit-down dining', 'Multi-cuisine menu', 'Good for occasions'],
    'Smart formal', 'A relaxed drive after dinner.',
    [
      [['Paneer Tikka', 320, T], ['Veg Seekh Kebab', 300, T], ['Chicken Tikka', 380, F]],
      [['Dal Makhani', 300, T], ['Paneer Lababdar', 360, T], ['Butter Chicken', 440, F], ['Veg Biryani', 340, T]],
      [['Fresh Lime Soda', 110, T], ['Virgin Mojito', 170, T], ['Cold Coffee', 160, T]],
      [['Gulab Jamun', 120, T], ['Ice Cream Sundae', 200, T]],
    ]),
  jabalpur('restaurant', 'jb-traffic', 'Traffic Jab', 'Vibrant', '🚦', 'Multi-cuisine · Hangout',
    'A popular hangout among locals for a relaxed, social meal.',
    ['Social hangout', 'Multi-cuisine', 'Easy and casual'],
    'Casual', 'Take a walk or drive after dinner.',
    [
      [['French Fries', 130, T], ['Crispy Corn', 190, T], ['Chicken 65', 280, F]],
      [['Veg Noodles', 200, T], ['Paneer Tikka Pizza', 320, T], ['Veg Burger', 200, T], ['Chicken Biryani', 300, F]],
      [['Fresh Lime Soda', 90, T], ['Cold Coffee', 130, T], ['Mojito', 150, T]],
      [['Brownie', 150, T], ['Ice Cream', 100, T]],
    ]),
  jabalpur('street', 'jb-fuhara', 'Fuhara Chowk (sweets & rabri)', 'Casual', '🍮', 'Street desserts · Sweets',
    'The place for khowa jalebi and rabri.',
    ['Khowa jalebi', 'Fresh rabri', 'A true local treat'],
    'Comfortable casual', 'Walk off the sweets around the market.',
    [
      [['Samosa', 30, T], ['Kachori', 35, T], ['Dahi Vada', 60, T]],
      [['Poha', 40, T], ['Poori Sabzi', 70, T], ['Chole Bhature', 90, T]],
      [['Masala Chai', 20, T], ['Sweet Lassi', 50, T], ['Badam Milk', 60, T]],
      [['Khowa Jalebi', 80, T], ['Rabri', 90, T], ['Gulab Jamun', 40, T]],
    ]),

  /* ----------------------------- Ahmedabad --------------------------- */
  ahmedabad('restaurant', 'ah-agashiye', 'Agashiye (The House of MG)', 'Romantic', '🏛️', 'Gujarati thali · Heritage rooftop · Vegetarian',
    'A heritage rooftop serving a daily-changing vegetarian thali.',
    ['Heritage rooftop', 'Daily-changing thali', 'Strictly vegetarian'],
    'Smart casual or ethnic', 'Wander the old-city lanes near the heritage house.',
    [
      [['Dhokla Plate', 120, T], ['Khandvi', 120, T], ['Fafda Jalebi', 140, T]],
      [['Khichdi & Kadhi', 320, T], ['Rooftop Thali (per person)', 450, T, 'Daily-changing vegetarian thali'], ['Kathiyawadi Platter', 480, T]],
      [['Masala Chaas', 70, T], ['Masala Chai', 80, T], ['Kokum Sharbat', 110, T]],
      [['Basundi', 150, T], ['Hand-churned Ice Cream', 180, T]],
    ]),
  ahmedabad('cafe', 'ah-green', 'The Green House (House of MG)', 'Cozy', '🌿', 'Café · Courtyard · Juices',
    'A courtyard café with cold-pressed juices, homemade ice cream and continental favourites.',
    ['Heritage courtyard', 'Cold-pressed juices', 'Homemade ice cream'],
    'Relaxed smart casual', 'Walk the old city after your meal.',
    [
      [['Cheese Garlic Toast', 240, T], ['Bruschetta', 260, T], ['Hummus & Pita', 280, T]],
      [['Gujarati Thali (small)', 380, T], ['Veg Pasta', 420, T], ['Wood-fired Pizza', 460, T]],
      [['Filter Coffee', 140, T], ['Iced Tea', 180, T], ['Cold-pressed Juice', 220, T]],
      [['Homemade Ice Cream', 180, T], ['Chocolate Brownie', 220, T]],
    ]),
  ahmedabad('cafe', 'ah-wagh', 'Wagh Bakri Tea Lounge', 'Cozy', '🫖', 'Tea lounge · Snacks',
    'A tea lounge for signature masala chai, lemongrass and saffron brews.',
    ['Signature chai', 'Flavoured brews', 'Light snacks'],
    'Relaxed casual', 'Pick up a tea blend to take home.',
    [
      [['Samosa', 60, T], ['Khakhra', 80, T], ['Veg Sandwich', 120, T]],
      [['Maska Bun', 90, T], ['Grilled Sandwich', 160, T], ['Pasta', 240, T]],
      [['Masala Chai', 60, T], ['Lemongrass Chai', 70, T], ['Saffron Chai', 90, T], ['Iced Tea', 110, T]],
      [['Cookies', 80, T], ['Brownie', 120, T]],
    ]),
  ahmedabad('restaurant', 'ah-vishalla', 'Vishalla', 'Vibrant', '🪘', 'Gujarati thali · Cultural village',
    'A cultural-village restaurant with folk music and traditional Gujarati thalis.',
    ['Folk music', 'Traditional thali', 'Rustic charm'],
    'Ethnic or casual', 'Wander the village grounds after your meal.',
    [
      [['Dhokla', 100, T], ['Khandvi', 110, T], ['Patra', 110, T]],
      [['Khichdi & Kadhi', 280, T], ['Bajra Rotla & Ringan Oro', 320, T], ['Traditional Gujarati Thali (per person)', 650, T]],
      [['Chaas', 60, T], ['Masala Chai', 60, T], ['Aam Panna', 100, T]],
      [['Shrikhand', 140, T], ['Basundi', 140, T]],
    ]),
  ahmedabad('restaurant', 'ah-chandra', 'Chandravilas', 'Casual', '🥣', 'Gujarati snacks · Chai',
    'Classic dhokla, khandvi and fafda with masala chai.',
    ['Gujarati snacks', 'Masala chai', 'Classic and simple'],
    'Comfortable casual', 'A short walk around the old city.',
    [
      [['Fafda', 70, T], ['Dhokla', 80, T], ['Khandvi', 90, T]],
      [['Thepla & Chundo', 140, T], ['Undhiyu & Puri', 220, T], ['Gujarati Thali', 260, T]],
      [['Masala Chai', 30, T], ['Chaas', 40, T], ['Jaljeera', 60, T]],
      [['Jalebi', 70, T], ['Mohanthal', 90, T]],
    ]),
  ahmedabad('street', 'ah-manek', 'Manek Chowk (night food market)', 'Vibrant', '🌙', 'Street food · Night market',
    'The old city’s square turns into a street-food paradise at night.',
    ['Night market', 'Fafda, bhaji pav, Gujarati pizza', 'Kulfi and masala chaas'],
    'Casual, comfortable shoes', 'Browse the lit-up stalls and end with kulfi.',
    [
      [['Dabeli', 40, T], ['Fafda', 60, T], ['Bhaji Pav', 100, T]],
      [['Pani Puri', 50, T], ['Sandwich', 100, T], ['Pulav', 120, T], ['Gujarati Pizza', 160, T]],
      [['Masala Chai', 20, T], ['Masala Chaas', 40, T], ['Cold Drink', 40, T]],
      [['Jalebi', 60, T], ['Kulfi', 90, T], ['Faluda', 110, T]],
    ]),

  /* ------------------------------- Jaipur ---------------------------- */
  jaipur('cafe', 'jp-tapri', 'Tapri Central', 'Cozy', '🍵', 'Tea · Rooftop café',
    'A tea-and-snacks café with a rooftop, known for around 100 tea varieties.',
    ['About 100 teas', 'Rooftop views', 'Fusion Rajasthani snacks'],
    'Relaxed casual', 'Walk through the park opposite the café.',
    [
      [['Namkeen Shots', 120, T], ['Tadka Maggie', 130, T], ['Cheese Vada Pav', 140, T]],
      [['Veg Sandwich', 160, T], ['Paneer Roll', 200, T], ['Pasta', 240, T]],
      [['Cutting Chai', 40, T], ['Masala Chai', 60, T], ['Hibiscus Iced Tea', 140, T]],
      [['Gulab Jamun', 90, T], ['Brownie', 140, T]],
    ]),
  jaipur('cafe', 'jp-anokhi', 'Anokhi Café', 'Cozy', '🌾', 'Organic café · Bistro',
    'An organic café with a simple, cheerful bistro feel.',
    ['Organic food', 'Cheerful bistro', 'Evening tea'],
    'Relaxed smart casual', 'Browse nearby boutiques after your tea.',
    [
      [['Bruschetta', 260, T], ['Hummus & Pita', 280, T], ['Salad of the Day', 300, T]],
      [['Grilled Sandwich', 340, T], ['Quiche & Salad', 380, T], ['Penne Pesto', 420, T]],
      [['Filter Coffee', 120, T], ['Iced Tea', 160, T], ['Fresh Juice', 180, T]],
      [['Brownie', 200, T], ['Carrot Cake', 220, T]],
    ]),
  jaipur('restaurant', 'jp-1135', '1135 AD', 'Romantic', '🏰', 'Mughlai · Rajasthani · North Indian',
    'Royal ambience with sunset views near Amer.',
    ['Imperial décor', 'Sunset views', 'Mughlai and Rajasthani menu'],
    'Smart formal', 'A relaxed evening walk around the Amer area.',
    [
      [['Paneer Tikka', 560, T], ['Dahi Ke Kebab', 580, T], ['Laal Maas Kebab', 720, F]],
      [['Dal Baati Churma', 640, T], ['Paneer Lababdar', 720, T], ['Murgh Korma', 880, F], ['Laal Maas', 980, F]],
      [['Masala Chai', 180, T], ['Fresh Lime Soda', 220, T], ['Mocktail', 380, T]],
      [['Gulab Jamun', 320, T], ['Ghevar', 360, T]],
    ]),
  jaipur('restaurant', 'jp-lmb', 'Laxmi Mishtan Bhandar (LMB)', 'Casual', '🥘', 'Rajasthani · Sweets · Thali',
    'The epicentre of Rajasthani flavours: kachori, ghewar and dal baati churma.',
    ['Rajasthani thali', 'Famous sweets', 'Old-city institution'],
    'Comfortable casual', 'Walk the old-city bazaars afterwards.',
    [
      [['Samosa', 50, T], ['Pyaaz Kachori', 60, T], ['Mirchi Vada', 60, T]],
      [['Dal Baati Churma', 320, T], ['Paneer Butter Masala & Roti', 340, T], ['Rajasthani Thali', 420, T]],
      [['Masala Chai', 50, T], ['Chaas', 60, T], ['Sweet Lassi', 90, T]],
      [['Rasmalai', 140, T], ['Malpua', 150, T], ['Ghewar', 180, T]],
    ]),
  jaipur('restaurant', 'jp-rawat', 'Rawat Mishthan Bhandar', 'Casual', '🥟', 'Pyaaz kachori · Sweets',
    'Famous for pyaaz kachori with mirchi bada and sweet lassi.',
    ['Pyaaz kachori', 'Mirchi bada', 'Sweet lassi'],
    'Comfortable casual', 'Pick up sweets and take a short walk.',
    [
      [['Mirchi Bada', 50, T], ['Pyaaz Kachori', 50, T], ['Mawa Kachori', 70, T]],
      [['Dahi Bhalla', 90, T], ['Samosa Chaat', 90, T], ['Kachori Sabzi Plate', 110, T]],
      [['Masala Chai', 30, T], ['Chaas', 40, T], ['Sweet Lassi', 80, T]],
      [['Rabri', 120, T], ['Ghevar', 150, T]],
    ]),

  /* ------------------------------ Lucknow ---------------------------- */
  lucknow('restaurant', 'lk-tunday', 'Tunday Kababi', 'Casual', '🍢', 'Awadhi · Kebabs',
    'The legendary Aminabad kebab house, serving since 1905.',
    ['Galouti kebab', 'Since 1905', 'Awadhi classic'],
    'Comfortable casual', 'Wander around Aminabad after your kebabs.',
    [
      [['Seekh Kebab', 150, F], ['Galouti Kebab', 160, F], ['Boti Kebab', 180, F]],
      [['Chicken Biryani', 220, F], ['Mutton Biryani', 260, F], ['Mutton Korma', 280, F], ['Sheermal (pair)', 60, T]],
      [['Masala Soda', 60, T], ['Cold Drink', 50, T], ['Lassi', 80, T]],
      [['Phirni', 70, T], ['Shahi Tukda', 90, T]],
    ]),
  lucknow('restaurant', 'lk-dast', 'Dastarkhwan', 'Romantic', '🍽️', 'Awadhi cuisine',
    'Authentic Awadhi cuisine with rich, aromatic flavours.',
    ['Awadhi specialities', 'Rich flavours', 'Hazratganj and Gomti Nagar'],
    'Smart casual', 'Take an evening stroll around Hazratganj.',
    [
      [['Paneer Tikka', 320, T], ['Galouti Kebab', 380, F], ['Kakori Kebab', 420, F]],
      [['Dal Makhani', 340, T], ['Paneer Lababdar', 380, T], ['Murgh Korma', 480, F], ['Awadhi Biryani', 520, F]],
      [['Fresh Lime Soda', 120, T], ['Rose Sharbat', 140, T], ['Masala Chai', 80, T]],
      [['Phirni', 180, T], ['Shahi Tukda', 220, T]],
    ]),
  lucknow('restaurant', 'lk-idris', 'Idris Biryani', 'Casual', '🍚', 'Biryani · Old city',
    'Old-world charm and fragrant biryani in the old city.',
    ['Fragrant biryani', 'Old-city charm', 'Great value'],
    'Comfortable casual', 'Walk the old-city lanes afterwards.',
    [
      [['Veg Cutlet', 90, T], ['Seekh Kebab', 140, F], ['Chicken Tikka', 200, F]],
      [['Veg Biryani', 160, T], ['Chicken Biryani', 200, F], ['Chicken Korma', 240, F], ['Mutton Biryani', 280, F]],
      [['Masala Chai', 30, T], ['Cold Drink', 50, T], ['Lassi', 70, T]],
      [['Phirni', 60, T], ['Zarda', 80, T]],
    ]),
  lucknow('restaurant', 'lk-royal', 'Royal Café', 'Vibrant', '🥘', 'Chaat · North Indian',
    'Known for its chaat and North Indian flavours.',
    ['Great chaat', 'North Indian menu', 'Lively and busy'],
    'Smart casual', 'Walk around the neighbourhood and share a kulfi.',
    [
      [['Papdi Chaat', 90, T], ['Dahi Bhalla', 90, T], ['Aloo Tikki Chaat', 100, T]],
      [['Dal Makhani', 260, T], ['Veg Biryani', 240, T], ['Paneer Tikka Masala', 320, T], ['Butter Naan Basket', 120, T]],
      [['Masala Soda', 60, T], ['Lassi', 80, T], ['Cold Coffee', 120, T]],
      [['Gulab Jamun', 70, T], ['Kulfi Falooda', 140, T]],
    ]),
  lucknow('cafe', 'lk-tea', 'Sharma Tea Stall', 'Casual', '☕', 'Tea stall · Kulhad chai',
    'A beloved tea stall for kulhad chai and simple snacks.',
    ['Kulhad chai', 'Local favourite', 'Budget-friendly'],
    'Casual', 'Take a relaxed walk with your chai.',
    [
      [['Samosa', 20, T], ['Bread Pakora', 30, T], ['Bun Maska', 30, T]],
      [['Poha', 40, T], ['Veg Sandwich', 60, T], ['Maska Bun & Chai', 60, T]],
      [['Masala Chai', 20, T], ['Kulhad Chai', 25, T], ['Lemon Tea', 20, T]],
      [['Jalebi', 30, T], ['Malai Makhan (seasonal)', 60, T]],
    ]),

  /* ----------------------------- Chandigarh -------------------------- */
  chandigarh('restaurant', 'cd-cafe17', 'Café 17 (Taj Chandigarh)', 'Romantic', '🍽️', 'All-day dining · Hotel café',
    'Upscale all-day dining inside Taj Chandigarh.',
    ['Hotel dining', 'All-day menu', 'Celebrations'],
    'Smart casual to formal', 'A relaxed evening walk around Sector 17.',
    [
      [['Soup of the Day', 420, T], ['Bruschetta', 480, T], ['Chicken Satay', 620, F]],
      [['Dal Makhani', 680, T], ['Pasta Primavera', 720, T], ['Butter Chicken & Naan', 880, F], ['Grilled Fish', 980, F]],
      [['Cappuccino', 280, T], ['Iced Tea', 300, T], ['Fresh Juice', 320, T]],
      [['Cheesecake', 460, T], ['Chocolate Fondant', 480, T]],
    ]),
  chandigarh('cafe', 'cd-ich', 'Indian Coffee House (Sector 17)', 'Casual', '📚', 'South Indian · Coffee',
    'A coffee spot that has drawn crowds for over 60 years, known for dosas and vadas.',
    ['60+ years of history', 'Dosas and vadas', 'Budget-friendly'],
    'Relaxed casual', 'Stroll through the Sector 17 plaza.',
    [
      [['Medu Vada', 70, T], ['Idli Sambar', 80, T], ['Veg Cutlet', 90, T]],
      [['Veg Sandwich', 100, T], ['Masala Dosa', 130, T], ['Uttapam', 130, T]],
      [['Tea', 30, T], ['Filter Coffee', 50, T], ['Cold Coffee', 90, T]],
      [['Gulab Jamun', 70, T], ['Ice Cream', 80, T]],
    ]),
  chandigarh('cafe', 'cd-akaasa', 'Akaasa Cafe', 'Vibrant', '🎪', 'Street-food café',
    'A street-food-style café in Sector 17 (around ₹800 for two).',
    ['Street-food menu', 'Easy on the pocket', 'Lively'],
    'Smart casual', 'Walk around Sector 17 afterwards.',
    [
      [['Chilli Potato', 160, T], ['Spring Rolls', 180, T], ['Chaat Platter', 190, T]],
      [['Veg Burger', 220, T], ['Paneer Tikka Roll', 260, T], ['Chicken Wrap', 300, F], ['Pasta', 320, T]],
      [['Masala Chai', 60, T], ['Cold Coffee', 160, T], ['Mojito', 180, T]],
      [['Brownie', 180, T], ['Ice Cream Sundae', 200, T]],
    ]),
  chandigarh('restaurant', 'cd-qisa', 'Qisa', 'Cozy', '🌴', 'South Indian',
    'A South Indian restaurant in Sector 17.',
    ['South Indian menu', 'Relaxed dining', 'Great dosas'],
    'Smart casual', 'Take a walk through the plaza.',
    [
      [['Medu Vada', 220, T], ['Mini Idli', 240, T], ['Chicken 65', 380, F]],
      [['Masala Dosa', 340, T], ['Veg Biryani', 380, T], ['Appam & Stew', 420, T], ['Chettinad Chicken', 520, F]],
      [['Buttermilk', 100, T], ['Filter Coffee', 140, T], ['Tender Coconut', 160, T]],
      [['Payasam', 180, T], ['Elaneer Payasam', 220, T]],
    ]),
  chandigarh('restaurant', 'cd-rhap', 'Rhapsody', 'Vibrant', '🎷', 'Multi-cuisine',
    'A multi-cuisine restaurant with a wide menu — Italian, Chinese, North Indian, burgers and more.',
    ['Wide menu', 'Biryani to burgers', 'Great for groups'],
    'Smart casual', 'Walk it off in the Sector 17 plaza.',
    [
      [['Garlic Bread', 240, T], ['Paneer Tikka', 360, T], ['Chicken Wings', 420, F]],
      [['Veg Burger', 320, T], ['Veg Biryani', 380, T], ['Penne Arrabbiata', 420, T], ['Butter Chicken & Naan', 520, F]],
      [['Fresh Lime Soda', 120, T], ['Cold Coffee', 220, T], ['Mojito', 240, T]],
      [['Brownie Sundae', 280, T], ['Tiramisu', 320, T]],
    ]),

  /* ------------------------------- Nagpur ---------------------------- */
  nagpur('restaurant', 'ng-pintu', 'Pintu Saoji', 'Casual', '🌶️', 'Saoji · Spicy Vidarbha cuisine',
    'Saoji cuisine from Vidarbha, known for its peppery heat.',
    ['Saoji specialities', 'Spicy and bold', 'Local favourite'],
    'Comfortable casual', 'Cool down with a sweet after your meal.',
    [
      [['Egg Bhurji', 150, F], ['Paneer Fry', 240, T], ['Saoji Chicken Fry', 280, F], ['Mutton Kheema', 320, F]],
      [['Jowar Roti (2)', 40, T], ['Patodi Rassa', 220, T], ['Saoji Chicken Curry', 340, F], ['Saoji Mutton Curry', 420, F]],
      [['Masala Chai', 20, T], ['Buttermilk', 40, T], ['Cold Drink', 50, T]],
      [['Gulab Jamun', 60, T], ['Rasgulla', 60, T]],
    ]),
  nagpur('restaurant', 'ng-rahi', 'Rahi Saoji', 'Casual', '🍖', 'Saoji · Spicy Vidarbha cuisine',
    'Saoji flavours at Pratap Nagar.',
    ['Authentic Saoji', 'Peppery curries', 'Hearty and filling'],
    'Comfortable casual', 'A short drive or a walk to cool off.',
    [
      [['Egg Bhurji', 140, F], ['Paneer Fry', 230, T], ['Saoji Chicken Fry', 270, F]],
      [['Jowar Roti (2)', 40, T], ['Patodi Rassa', 210, T], ['Saoji Chicken Curry', 330, F], ['Saoji Mutton Curry', 410, F]],
      [['Masala Chai', 20, T], ['Buttermilk', 40, T], ['Cold Drink', 50, T]],
      [['Gulab Jamun', 60, T], ['Rasgulla', 60, T]],
    ]),
  nagpur('restaurant', 'ng-hald', 'Haldiram’s (Dharampeth)', 'Casual', '🥨', 'Vegetarian · Sweets · Snacks',
    'A reliable vegetarian stop for snacks, sweets and fast food.',
    ['Vegetarian', 'Sweets and snacks', 'Open all day'],
    'Comfortable casual', 'Pick up sweets to take along.',
    [
      [['Dahi Bhalla', 120, T], ['Samosa Chaat', 120, T], ['Raj Kachori', 140, T]],
      [['Chole Bhature', 200, T], ['Pav Bhaji', 220, T], ['Hakka Noodles', 240, T], ['Veg Thali', 320, T]],
      [['Masala Chai', 50, T], ['Sweet Lassi', 90, T], ['Cold Coffee', 120, T]],
      [['Gulab Jamun', 90, T], ['Rasmalai', 120, T], ['Kaju Katli (100 g)', 160, T]],
    ]),
  nagpur('restaurant', 'ng-creative', 'The Creative Kitchen (Radisson Blu)', 'Romantic', '🍽️', 'Multi-cuisine · Buffet & à la carte',
    'A hotel restaurant with buffet and à la carte options across Indian, Chinese and continental.',
    ['Buffet and à la carte', 'Hotel setting', 'Wide cuisine range'],
    'Smart casual to formal', 'A quiet drive around the city afterwards.',
    [
      [['Caesar Salad', 480, T], ['Dim Sum Basket', 520, T], ['Tandoori Platter', 680, F]],
      [['Dal Makhani & Naan', 640, T], ['Thai Green Curry & Rice', 720, T], ['Grilled Chicken Steak', 880, F], ['Dinner Buffet (per person)', 1450, F]],
      [['Cappuccino', 260, T], ['Fresh Juice', 320, T], ['Mocktail', 380, T]],
      [['Rasmalai', 320, T], ['Chocolate Fondant', 480, T]],
    ]),
  nagpur('restaurant', 'ng-gayatri', 'Gayatri Bhojnalaya', 'Casual', '🍲', 'Vegetarian · Thali',
    'A simple Indian restaurant that fills up for Sunday dinners.',
    ['Home-style meals', 'Busy Sunday evenings', 'Pocket-friendly'],
    'Comfortable casual', 'A relaxed walk after dinner.',
    [
      [['Samosa', 40, T], ['Dahi Vada', 80, T], ['Paneer Pakoda', 140, T]],
      [['Dal Fry & Rice', 160, T], ['Veg Thali', 220, T], ['Paneer Butter Masala & Roti', 240, T], ['Tarri Poha', 60, T]],
      [['Masala Chai', 25, T], ['Chaas', 40, T], ['Sweet Lassi', 70, T]],
      [['Gulab Jamun', 60, T], ['Shrikhand', 90, T]],
    ]),
  nagpur('cafe', 'ng-corr', 'Corridor Seven Coffee Roasters', 'Cozy', '☕', 'Specialty coffee · Café',
    'A specialty coffee roaster with a loyal following across many cities.',
    ['Specialty coffee', 'Calm and modern', 'Roasted in-house'],
    'Relaxed smart casual', 'Take a coffee to go and stroll nearby.',
    [
      [['Banana Bread', 220, T], ['Cheese Toast', 200, T], ['Croissant', 240, T]],
      [['Veg Sandwich', 320, T], ['Chicken Sandwich', 380, F], ['Pesto Pasta', 420, T]],
      [['Cappuccino', 220, T], ['Flat White', 240, T], ['Cold Brew', 260, T]],
      [['Brownie', 220, T], ['Cheesecake', 280, T]],
    ]),
  nagpur('cafe', 'ng-three', 'Three Beans Coffee Bar', 'Cozy', '🫘', 'Coffee · Desserts · Italian bites',
    'Coffee, desserts and Italian-style bites.',
    ['Good coffee', 'Pizzas and pastas', 'Dessert menu'],
    'Relaxed casual', 'Share a dessert and stroll nearby.',
    [
      [['Garlic Bread', 180, T], ['Cheese Fries', 200, T], ['Nachos', 240, T]],
      [['Grilled Sandwich', 240, T], ['Margherita Pizza', 320, T], ['Pasta Alfredo', 340, T], ['Chicken Pizza', 400, F]],
      [['Cappuccino', 170, T], ['Cold Coffee', 190, T], ['Hot Chocolate', 200, T]],
      [['Brownie', 180, T], ['Waffle with Ice Cream', 240, T]],
    ]),
  nagpur('cafe', 'ng-godwit', 'Godwit Cafe', 'Vibrant', '🌿', 'Café · Continental · Asian',
    'A Civil Lines café with a wide continental, Italian and Asian menu.',
    ['Wide menu', 'Civil Lines location', 'Great desserts'],
    'Smart casual', 'Walk around Civil Lines after dinner.',
    [
      [['Spring Rolls', 260, T], ['Bruschetta', 280, T], ['Chicken Wings', 360, F]],
      [['Penne Pesto', 420, T], ['Margherita Pizza', 420, T], ['Thai Curry & Rice', 460, T], ['Butter Chicken & Naan', 520, F]],
      [['Iced Tea', 200, T], ['Cold Coffee', 220, T], ['Mojito', 240, T]],
      [['Chocolate Brownie', 260, T], ['Tiramisu', 300, T]],
    ]),

  /* ------------------------------- Kochi ----------------------------- */
  kochi('cafe', 'kc-kashi', 'Kashi Art Café', 'Cozy', '🎨', 'Art café · Breakfast',
    'An art-gallery café in Fort Kochi, famous for breakfast and chocolate cake.',
    ['Art gallery café', 'Great breakfast', 'Chocolate cake'],
    'Relaxed casual', 'Wander the galleries and lanes of Fort Kochi.',
    [
      [['Banana Pancake', 280, T], ['Hummus & Toast', 320, T], ['Fish Cutlet', 340, F]],
      [['Veg Sandwich', 320, T], ['Chicken Sandwich', 380, F], ['Eggs Benedict', 420, F], ['Pasta of the Day', 460, T]],
      [['Filter Coffee', 140, T], ['Fresh Juice', 180, T], ['Cappuccino', 200, T]],
      [['Carrot Cake', 260, T], ['Chocolate Cake', 280, T]],
    ]),
  kochi('cafe', 'kc-david', 'David Hall Art Gallery Café', 'Cozy', '🍕', 'Café · Bakery · Wood-fired pizza',
    'A café-bakery with a wood-fired pizza space, ideal for a slower break.',
    ['Wood-fired pizza', 'Bakery', 'Gallery setting'],
    'Relaxed casual', 'Walk along the Fort Kochi waterfront.',
    [
      [['Garlic Bread', 220, T], ['Bruschetta', 260, T], ['Fish Fingers', 340, F]],
      [['Penne Arrabbiata', 420, T], ['Wood-fired Margherita', 460, T], ['Wood-fired Chicken Pizza', 560, F]],
      [['Fresh Lime Soda', 140, T], ['Cappuccino', 180, T], ['Iced Tea', 180, T]],
      [['Brownie', 220, T], ['Cheesecake', 260, T]],
    ]),
  kochi('restaurant', 'kc-puttu', 'Dhe Puttu', 'Casual', '🍚', 'Kerala · Puttu',
    'Puttu served in many ways, with sweet black coffee in bamboo trays.',
    ['Many kinds of puttu', 'Bamboo-tray serving', 'Sweet black coffee'],
    'Comfortable casual', 'Walk along the Fort Kochi streets afterwards.',
    [
      [['Banana Fritters', 120, T], ['Vegetable Cutlet', 140, T], ['Chicken Fry', 260, F]],
      [['Puttu & Kadala Curry', 220, T], ['Chocolate Puttu', 240, T], ['Appam & Stew', 260, T], ['Chicken Puttu', 320, F]],
      [['Lime Juice', 80, T], ['Sweet Black Coffee', 80, T], ['Tender Coconut', 100, T]],
      [['Banana Halwa', 120, T], ['Elaneer Payasam', 140, T]],
    ]),
  kochi('restaurant', 'kc-kayees', 'Kayees Rahmathulla Hotel', 'Casual', '🍛', 'Biryani · Mattancherry',
    'A Mattancherry biryani institution since 1948, cooked in pure ghee.',
    ['Since 1948', 'Famous biryani', 'Prompt and filling'],
    'Comfortable casual', 'Explore Mattancherry’s spice lanes afterwards.',
    [
      [['Egg Roast', 90, F], ['Chicken Cutlet', 120, F], ['Fish Fry', 200, F]],
      [['Veg Pulao', 160, T], ['Chicken Biryani', 280, F], ['Fish Biryani (Fridays)', 300, F], ['Mutton Biryani', 340, F]],
      [['Tea', 20, T], ['Sulaimani', 30, T], ['Lime Soda', 60, T]],
      [['Payasam', 80, T], ['Caramel Pudding', 90, T]],
    ]),
  kochi('restaurant', 'kc-fort', 'Fort House Restaurant', 'Romantic', '🌊', 'Kerala · Waterfront',
    'Waterfront dining with authentic Kerala cuisine in Fort Kochi.',
    ['Waterfront setting', 'Authentic Kerala cuisine', 'Serene evenings'],
    'Smart casual', 'A quiet walk along the Fort Kochi waterfront.',
    [
      [['Vegetable Cutlet', 260, T], ['Karimeen Fry', 480, F], ['Prawn Roast', 540, F]],
      [['Appam with Veg Stew', 420, T], ['Malabar Chicken Curry', 480, F], ['Kerala Fish Curry & Rice', 520, F], ['Prawn Moilee', 640, F]],
      [['Filter Coffee', 120, T], ['Fresh Lime Soda', 140, T], ['Tender Coconut Water', 160, T]],
      [['Banana Halwa', 180, T], ['Elaneer Payasam', 220, T]],
    ]),
  kochi('restaurant', 'kc-history', 'History Restaurant (Brunton Boatyard)', 'Romantic', '📜', 'Heritage Kerala · Seafood',
    'Forgotten old Kerala recipes, each served with its backstory.',
    ['Heritage recipes', 'Seafood', 'Storytelling menu'],
    'Smart casual to formal', 'Walk the waterfront as the lights come on.',
    [
      [['Vegetable Moilee Cups', 480, T], ['Pepper Calamari', 620, F], ['Prawn Cocktail', 720, F]],
      [['Veg Ishtu & Appam', 640, T], ['Syrian Christian Chicken Roast', 780, F], ['Prawn Curry & Rice', 840, F], ['Meen Pollichathu', 880, F]],
      [['Filter Coffee', 200, T], ['Fresh Lime Soda', 220, T], ['Nannari Sharbat', 240, T]],
      [['Payasam', 340, T], ['Caramelized Banana', 360, T]],
    ]),
]
